use std::{io, ops::Deref, sync::Arc};

use edr_eth::B256;
use edr_evm::RandomHashGenerator;
use napi::{bindgen_prelude::Buffer, Status};
use napi_derive::napi;
use parking_lot::Mutex;
use tracing_subscriber::{prelude::*, EnvFilter, Registry};

use crate::cast::TryCast;

#[napi]
#[derive(Debug)]
pub struct EdrContext {
    inner: Arc<Context>,
}

impl Deref for EdrContext {
    type Target = Arc<Context>;

    fn deref(&self) -> &Self::Target {
        &self.inner
    }
}

#[napi]
impl EdrContext {
    #[doc = "Creates a new [`EdrContext`] instance. Should only be called once!"]
    #[napi(constructor)]
    pub fn new() -> napi::Result<Self> {
        let context =
            Context::new().map_err(|e| napi::Error::new(Status::GenericFailure, e.to_string()))?;

        Ok(Self {
            inner: Arc::new(context),
        })
    }

    #[doc = "Overwrites the next value generated by the state root generator with the provided seed."]
    #[napi]
    pub fn set_state_root_generator_seed(&self, seed: Buffer) -> napi::Result<()> {
        let seed = TryCast::<B256>::try_cast(seed)?;

        self.inner.state_root_generator.lock().set_next(seed);

        Ok(())
    }
}

#[derive(Debug)]
pub struct Context {
    pub state_root_generator: Arc<Mutex<RandomHashGenerator>>,
    #[cfg(feature = "tracing")]
    _tracing_write_guard: tracing_flame::FlushGuard<std::io::BufWriter<std::fs::File>>,
}

impl Context {
    /// Creates a new [`Context`] instance. Should only be called once!
    pub fn new() -> io::Result<Self> {
        let fmt_layer = tracing_subscriber::fmt::layer()
            .with_file(true)
            .with_line_number(true)
            .with_thread_ids(true)
            .with_target(false)
            .with_level(true)
            .with_filter(EnvFilter::from_default_env());

        let subscriber = Registry::default().with(fmt_layer);

        #[cfg(feature = "tracing")]
        let (flame_layer, guard) = {
            let (flame_layer, guard) =
                tracing_flame::FlameLayer::with_file("tracing.folded").unwrap();

            let flame_layer = flame_layer.with_empty_samples(false);
            (flame_layer, guard)
        };

        #[cfg(feature = "tracing")]
        let subscriber = subscriber.with(flame_layer);

        tracing::subscriber::set_global_default(subscriber)
            .expect("Could not set global default tracing subscriber");

        let state_root_generator = Arc::new(Mutex::new(RandomHashGenerator::with_seed(
            edr_defaults::STATE_ROOT_HASH_SEED,
        )));

        Ok(Self {
            state_root_generator,
            #[cfg(feature = "tracing")]
            _tracing_write_guard: guard,
        })
    }
}
