module.exports.slowImportsCommonIgnoredModules = [
  "chalk",
  "debug",
  "find-up",
  "fs-extra",
  "semver",
  "source-map-support/register",
  "@nomicfoundation/hardhat-ethers",
  "hardhat/config",
  "hardhat/plugins",
  "hardhat/types",
  "hardhat/types/runtime",
  "hardhat/builtin-tasks/task-names",
  "hardhat/internal/core/errors",
];
