[package]
name = "edr_solidity"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
edr_eth = { version = "0.2.0-dev", path = "../edr_eth" }
revm = { version = "6.1", default-features = false, features = ["dev", "serde", "std"] }
