language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"

os:
  - linux
  - osx

install:
  - npm install

script:
  - npm run test
  - npx codecov
  - npm run lint

branches:
  only:
    - master
