language: node_js

services:
  - docker

before_install:
  - docker pull ethereum/vyper:0.1.0b10

node_js:
  - "8"
  - "10"
  - "11"

install:
  - npm install
  - npx lerna bootstrap --no-ci

script:
  - npm run test
  - npm run lint
  - node scripts/check-dependencies.js

cache:
  npm: true
  directories:
    - $HOME/.npm
    - node_modules
    - packages/*/node_modules

branches:
  only:
    - master
