language: node_js

node_js:
  - "8"
  - "10"
  - "11"

install:
  - npm ci
  - npx lerna bootstrap --ci

script:
  - npm run test
  - npm run lint
  - node scripts/check-dependencies.js

cache: npm

branches:
  only:
    - master