codecov:
  branch: v-next
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
    notify_error: true

coverage:
  status:
    project: false
    patch: false

comment:
  show_carryforward_flags: true

flag_management:
  default_rules:
    carryforward: true

bundle_analysis:
  status: false
