[package]
name = "edr_rpc_server"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
async-rwlock = { version = "1.3.0", default-features = false }
async-trait = { version = "0.1.73", default-features = false }
axum = "0.6.18"
indexmap = { version = "2.0.0", default-features = false, features = ["std"] }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
hyper = { version = "0.14.27", default-features = false, features = ["server"] }
k256 = { version = "0.13.1", default-features = false, features = ["arithmetic", "ecdsa", "pkcs8", "precomputed-tables", "std"] }
parking_lot = { version = "0.12.1", default-features = false }
reqwest = { version = "0.11", features = ["blocking", "json"] }
edr_eth = { version = "0.2.0-dev", path = "../edr_eth", features = ["serde"] }
edr_evm = { version = "0.2.0-dev", path = "../edr_evm" }
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.89" }
sha3 = { version = "0.10.6", default-features = false }
thiserror = { version = "1.0.37", default-features = false }
tokio = { version = "1.21.2", default-features = false, features = ["macros"] }
tracing = { version = "0.1.37", default-features = false, features = ["std"] }

[dev-dependencies]
anyhow = "1.0.75"
edr_test_utils = { version = "0.2.0-dev", path = "../edr_test_utils" }
tempfile = "3.7.1"
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["fmt"] }

[build-dependencies]
cargo_toml = { version = "0.15.3", default-features = false }
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
toml = { version = "0.5.9", default-features = false }

[features]
## This feature needs to be accessible from integration tests. If it's not default, we'd have to run the integration
## tests `cargo test --features test-tools`
default = ["test-tools"]
test-tools = []
