// This file was autogenerated by Hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface A$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "A";
  readonly sourceName: "contracts/A.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220fa80377a08a97ad93ccb004c8ba5b1944699d70ad3012de9351c0bca77d0196664736f6c63430008160033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220fa80377a08a97ad93ccb004c8ba5b1944699d70ad3012de9351c0bca77d0196664736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "contracts/A.sol";
  readonly buildInfoId: "c6d3d46c7bda8aac0e4258c216012f50";
}

import "@ignored/hardhat-vnext/types/artifacts";
declare module "@ignored/hardhat-vnext/types/artifacts" {
  interface ArtifactMap {
    ["A"]: A$Type;
    ["contracts/A.sol:A"]: A$Type;
  }
}
