#!/bin/sh
#
# Intended to be in sync with .github/workflows/hardhat-core-ci.yml's
# test-edr-rs

if [ -z "${ALCHEMY_URL}" ] || [ -z "${INFURA_URL}" ]; then
  echo WARNING: skipping remote tests because the ALCHEMY_URL and INFURA_URL environment variables are not defined. Local test results may differ from those in CI.
  ALL_FEATURES="--features tracing,bench-once,serde,std"
else
  ALL_FEATURES=--all-features
fi

# Set -x  here to avoid printing secrets
set -xe

# Setting RUSTFLAGS env for clippy makes it not include custom rules
RUSTFLAGS=-Dwarnings cargo check --workspace --all-targets --profile bench ${ALL_FEATURES}
cargo clippy --all --all-targets ${ALL_FEATURES} -- -D warnings
cargo +nightly fmt --all -- --check
cargo test --doc --workspace ${ALL_FEATURES}
cargo test --workspace --all-targets ${ALL_FEATURES}
