#!/bin/sh -x
#
# Intended to be in sync with .github/workflows/hardhat-core-ci.yml's
# test-rethnet-rs

set -e

export RUSTFLAGS=-Dwarnings

if [ -z "${ALCHEMY_URL}" ]; then
  echo WARNING: skipping remote tests because the ALCHEMY_URL environment variable is not defined. Local test results may differ from those in CI.
  ALL_FEATURES="--features tracing,bench-once,serde,std"
else
  ALL_FEATURES=--all-features
fi

cargo check --workspace --all-targets --no-default-features --profile bench
cargo check --workspace --all-targets --profile bench ${ALL_FEATURES}
cargo test --workspace --all-targets ${ALL_FEATURES}
cargo test --doc --workspace ${ALL_FEATURES}
cargo clippy --all --all-targets ${ALL_FEATURES} -- -D warnings
cargo fmt --all -- --check
