name: Bug report
description: File a bug report
type: "Bug"
body:
  - type: input
    id: version
    attributes:
      label: "Version of Hardhat"
      description: "Run `npx hardhat --version` to get the version of Hardhat that you are using"
      placeholder: "1.2.3"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: "What happened?"
      description: "A brief description of what happened and what you expected to happen"
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Minimal reproduction steps"
      description: "Tell us the minimal steps needed to reproduce the bug"
    validations:
      required: true
  - type: input
    id: search-terms
    attributes:
      label: "Search terms"
      description: "Include the search terms you used before opening this issue. This will make it easier for others to find it."
