name: Feature request
description: Suggest a new feature
type: "Feature"
labels: ["status:needs-priority"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: "Describe the feature"
      description: "A description of what you would like us to add to Hardhat and your use case for it"
    validations:
      required: true
  - type: input
    id: search-terms
    attributes:
      label: "Search terms"
      description: "Include the search terms you used before opening this issue. This will make it easier for others to find it."
