name: Other issue
description: Other kind of issue. Please don't use this to ask questions
type: "Task"
body:
  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the issue"
      description: "A description of the issue you are experiencing."
    validations:
      required: true