/**
 * This function hashes its input with a NON cryptographic.
 *
 * This function is useful for creating unique identifiers based on some
 * input. You can be confident that there won't be any collision, as long
 * as the input is not generated by an attacker.
 *
 * The exact algorithm being used shouldn't matter.
 */
export async function createNonCryptographicHashBasedIdentifier(
  input: Buffer,
): Promise<Buffer> {
  const { createHash } = await import("crypto");

  return createHash("md5").update(input).digest();
}
