name: CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches:
      - "**"

jobs:
  test_on_windows:
    name: Test Ignition on Windows with Node 18
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_macos:
    name: Test Ignition on MacOS with Node 18
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  test_on_linux:
    name: Test Ignition on Ubuntu with Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Run tests
        run: pnpm test

  lint:
    name: Lint the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
