import type { ResolvedUserRemapping } from "./remapped-npm-packages-map.js";
import type { Remapping, Resolver } from "./types.js";
import type {
  ResolvedNpmPackage,
  ResolvedFile,
  FileContent,
  ProjectResolvedFile,
  NpmPackageResolvedFile,
} from "../../../../../types/solidity/resolved-file.js";
import type { UserRemappingError } from "../../../../../types/solidity.js";
import type { Result } from "../../../../../types/utils.js";

import path from "node:path";

import {
  HardhatError,
  assertHardhatInvariant,
} from "@nomicfoundation/hardhat-errors";
import { ensureError } from "@nomicfoundation/hardhat-utils/error";
import {
  FileNotFoundError,
  getFileTrueCase,
  readUtf8File,
} from "@nomicfoundation/hardhat-utils/fs";
import { shortenPath } from "@nomicfoundation/hardhat-utils/path";
import { analyze } from "@nomicfoundation/solidity-analyzer";
import * as resolve from "resolve.exports";

import { ResolvedFileType } from "../../../../../types/solidity/resolved-file.js";
import { AsyncMutex } from "../../../../core/async-mutex.js";
import {
  NpmPackageResolvedFileImplementation,
  ProjectResolvedFileImplementation,
} from "../resolved-file.js";

import {
  getDirectImportLocalDesambiguationPrefix,
  isLocalDirectImport,
} from "./imports-clasification.js";
import { parseNpmDirectImport } from "./npm-moudles-parsing.js";
import { RemappedNpmPackagesMap } from "./remapped-npm-packages-map.js";
import {
  applyValidRemapping,
  formatRemapping,
  selectBestRemapping,
} from "./remappings.js";
import {
  sourceNamePathJoin,
  sourceNamePathToFsPath,
} from "./source-name-utils.js";

// Things to note:
//  - This resolver assumes that the root of the project is the folder with the
//    closest package.json to the config file.
//  - Each file system file is resolved to a single ResolvedFile, with a unique
//    source name.
//  - Files within the project have their relative path as their source name.
//  - Files within npm packages have source names that start with `npm/` and
//    contain the package name and version. e.g. `npm/package@1.2.3/path.sol`.
//  - Files within npm packages that are part of a monorepo are resolved like
//    npm pacakges, but with the version `local`.
//  - This resolver fails if an import has a casing different from that of the
//    file system.
//  - We do not allow users to remap the imports present in files within npm
//    packages, by forbidding user remappings with context and starting with
//    `npm/`.
//  - We do allow users to remap imports of non-npm files, including remmapping
//    them into npm packages.
//  - Every import in an npm file is either relative or remapped by a remapping
//    generated by the resolver.
//  - A direct import (i.e. not relative) is considered to be local within the
//    the project/package if it is a bare file name (not in a directory), or if
//    the first directory exists in the project/package.
//  - The direct import "hardhat/console.sol" is a special case and it is never
//    considered to be local. And we only remap `hardhat/console.sol`.
//  - Local imports within the project may be remapped by user remappings, but
//    not by the resolver.
//  - Imports into npm packages are always remapped, if not by the user, by the
//    resolver.
//  - Direct local improts within npm package are always remapped by the
//    resolver.

interface ImportDoesntExistError {
  type: "IMPORT_DOESNT_EXIST";
  fromFsPath: string;
  importPath: string;
  userRemapping?: {
    originalUserRemapping: string;
    actualUserRemapping: string;
    remappingSource: "HardhatConfig" | string;
  };
  target: {
    // Only present if the import isn't into a project file
    npmPackage?: { name: string; version: string; rootFsPath: string };
    // The file we are trying to import
    subpath: string;
    // The file we were expecting to see in the file system after applying
    // pacakge.exports
    resolvedSubpath?: string;
  };
}

interface ImportInvalidCasingError {
  type: "IMPORT_INVALID_CASING";
  fromFsPath: string;
  importPath: string;
  userRemapping?: {
    originalUserRemapping: string;
    actualUserRemapping: string;
    remappingSource: "HardhatConfig" | string;
  };
  target: {
    // Only present if the import isn't into a project file
    npmPackage?: { name: string; version: string; rootFsPath: string };
    // The file we are trying to import
    subpath: string;
    // The file we were expecting to see in the file system after applying
    // pacakge.exports
    resolvedSubpath?: string;
  };
  correctCasing: string;
}

interface ImportWithInvalidNpmSyntaxError {
  type: "IMPORT_WITH_INVALID_NPM_SYNTAX";
  fromFsPath: string;
  importPath: string;
}

interface ImportOfUninstalledPackageError {
  type: "IMPORT_OF_UNINSTALLED_PACKAGE";
  fromFsPath: string;
  importPath: string;
  packageName: string;
}

interface ImportOfNpmPackageWithRemappingErrorsError {
  type: "IMPORT_OF_NPM_PACKAGE_WITH_REMAPPING_ERRORS";
  fromFsPath: string;
  importPath: string;
  packageName: string;
  remappingErrors: UserRemappingError[];
}

export class ResolverImplementation implements Resolver {
  readonly #projectRoot: string;
  readonly #npmPackageMap: RemappedNpmPackagesMap;

  /**
   * IMPORTANT: This mutex must be acquired before writing to any of the mutable
   * fields of this class. We do this by using the mutex in the public methods,
   * which don't call each other.
   */
  readonly #mutex = new AsyncMutex();

  /**
   * We use this map to ensure that we only resolve each file once.
   **/
  readonly #resolvedFileBySourceName: Map<string, ResolvedFile> = new Map();

  /**
   * A map of all the prefixes that an npm package needs to set as remappings
   * to avoid being affected by a remapping coming from the Hardhat config as
   * those normally don't have any context.
   *
   * For example, if a package `foo` has an import `import "dep/File.sol";`,
   * and the user remaps `dep/=nope/`, it could break `foo`'s import.
   *
   * To avoid this situation we set all the prefixes that `foo` needs unaffected
   * by the user remapping, with a higher precedence than user remappings.
   */
  readonly #localPrefixesByPackage: Map<ResolvedNpmPackage, Set<string>> =
    new Map();

  /**
   * Creates a new Resolver.
   *
   * @param projectRoot The absolute path to the Hardhat project root.
   * @param configUserRemappings The remappings provided by the user in their
   *  Hardhat config.
   */
  public static async create(
    projectRoot: string,
    configUserRemappings: string[],
  ): Promise<Result<Resolver, UserRemappingError[]>> {
    const result = await RemappedNpmPackagesMap.create(
      projectRoot,
      configUserRemappings,
    );

    if (result.success === false) {
      return result;
    }

    return {
      success: true,
      value: new ResolverImplementation(projectRoot, result.value),
    };
  }

  /**
   * Legacy version of the create method to make this compile while we work
   * on bubbling the errors.
   * @param projectRoot
   * @param configUserRemappings
   */
  public static async legacyCreate(
    projectRoot: string,
    configUserRemappings: string[],
  ): Promise<Resolver> {
    const result = await ResolverImplementation.create(
      projectRoot,
      configUserRemappings,
    );

    if (result.success === true) {
      return result.value;
    }

    throw new Error(
      "TODO: Remapping errors while creating a resolver: " +
        JSON.stringify(result.error, null, 2),
    );
  }

  private constructor(
    projectRoot: string,
    npmPackagesMap: RemappedNpmPackagesMap,
  ) {
    this.#projectRoot = projectRoot;
    this.#npmPackageMap = npmPackagesMap;
  }

  public async resolveProjectFile(
    absoluteFilePath: string,
  ): Promise<ProjectResolvedFile> {
    return this.#mutex.exclusiveRun(async () => {
      if (!absoluteFilePath.startsWith(this.#projectRoot)) {
        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.RESOLVING_INCORRECT_FILE_AS_PROJECT_FILE,
          {
            file: shortenPath(absoluteFilePath),
          },
        );
      }

      const relativeFilePath = path.relative(
        this.#projectRoot,
        absoluteFilePath,
      );

      // We first check if the file has already been resolved.
      //
      // Note that it may have received the right path, but with the wrong
      // casing. We don't care at this point, as it would just mean a cache
      // miss, and we proceed to get the right casing in that case.
      //
      // However, as most of the time these absolute paths are read from the file
      // system, they'd have the right casing in general.
      //
      // If we need to fetch the right casing, we'd have to recheck the cache,
      // to avoid re-resolving the file.
      let sourceName = fsPathToSourceNamePath(relativeFilePath);
      const existing = this.#resolvedFileBySourceName.get(sourceName);

      if (existing !== undefined) {
        /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions --
      The cache is type-unsafe, but we are sure this is a ProjectResolvedFile */
        return existing as ProjectResolvedFile;
      }

      let trueCaseFsPath: string;
      try {
        trueCaseFsPath = await getFileTrueCase(
          this.#projectRoot,
          relativeFilePath,
        );
      } catch (error) {
        ensureError(error, FileNotFoundError);

        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.RESOLVING_NONEXISTENT_PROJECT_FILE,
          { file: shortenPath(absoluteFilePath) },
          error,
        );
      }

      // Now that we have the correct casing, we "fix" the source name.
      sourceName = fsPathToSourceNamePath(trueCaseFsPath);

      // Maybe it was already resolved, so we need to check with the right
      // casing
      const resolvedWithTheRightCasing =
        this.#resolvedFileBySourceName.get(sourceName);
      if (resolvedWithTheRightCasing !== undefined) {
        /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions
      -- If it was, it's a ProjectResolvedFile */
        return resolvedWithTheRightCasing as ProjectResolvedFile;
      }

      const fsPathWithTheRightCasing = path.join(
        this.#projectRoot,
        trueCaseFsPath,
      );

      const resolvedFile: ProjectResolvedFile =
        new ProjectResolvedFileImplementation({
          sourceName,
          fsPath: fsPathWithTheRightCasing,
          content: await readFileContent(fsPathWithTheRightCasing),
        });

      this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

      return resolvedFile;
    });
  }

  public async resolveNpmDependencyFileAsRoot(
    npmModule: string,
  ): Promise<NpmPackageResolvedFile> {
    return this.#mutex.exclusiveRun(async () => {
      const parsedNpmModule = parseNpmDirectImport(npmModule);

      if (parsedNpmModule === undefined) {
        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.RESOLVE_NPM_FILE_WITH_INVALID_FORMAT,
          { module: npmModule },
        );
      }

      if (await isLocalDirectImport(this.#projectRoot, npmModule)) {
        const directory = getDirectImportLocalDesambiguationPrefix(npmModule);

        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.RESOLVE_NPM_FILE_CLASHES_WITH_LOCAL_FILES,
          {
            module: npmModule,
            directory,
          },
        );
      }

      // TODO: Apply remappings here

      const hardhatProejctNpmPackage =
        this.#npmPackageMap.getHardhatProjectPackage();

      const modulePackageName = parsedNpmModule.package;

      const npmPackage = await this.#resolveNpmPackage({
        from: hardhatProejctNpmPackage,
        installationName: modulePackageName,
      });

      assertHardhatInvariant(
        npmPackage !== hardhatProejctNpmPackage,
        "Resolving a local file as if it were an npm module",
      );

      const subpath = parsedNpmModule.subpath;
      const resolvedSubpath = resolveSubpathWithPackageExports(
        npmPackage,
        subpath,
      );

      const relativeFsPath = sourceNamePathToFsPath(resolvedSubpath);
      let trueCaseFsPath: string;
      try {
        trueCaseFsPath = await getFileTrueCase(
          npmPackage.rootFsPath,
          relativeFsPath,
        );
      } catch (error) {
        ensureError(error, FileNotFoundError);

        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.RESOLVE_NON_EXISTENT_NPM_ROOT,
          { module: npmModule },
          error,
        );
      }

      if (relativeFsPath !== trueCaseFsPath) {
        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.RESOLVE_WRONG_CASING_NPM_ROOT,
          { module: npmModule },
        );
      }

      const sourceName = sourceNamePathJoin(
        npmPackage.rootSourceName,
        // We use the subpath (pre-resolution) to create source names
        subpath,
      );

      const resolved = this.#resolvedFileBySourceName.get(sourceName);

      if (resolved !== undefined) {
        /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions
      -- If it was, it's a ProjectResolvedFile */
        return resolved as NpmPackageResolvedFile;
      }

      const fsPath = path.join(npmPackage.rootFsPath, trueCaseFsPath);

      const resolvedFile: NpmPackageResolvedFile =
        new NpmPackageResolvedFileImplementation({
          sourceName,
          fsPath,
          content: await readFileContent(fsPath),
          package: npmPackage,
        });

      this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

      return resolvedFile;
    });
  }

  public async resolveImport(
    from: ResolvedFile,
    importPath: string,
  ): Promise<ResolvedFile> {
    return this.#mutex.exclusiveRun(async () => {
      let directImport = importPath;

      // We first validate that the import path doesn't include a windows
      // separator.
      if (path.sep !== "/" && importPath.includes(path.sep)) {
        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.IMPORT_PATH_WITH_WINDOWS_SEPARATOR,
          {
            importPath,
            from: shortenPath(from.fsPath),
          },
        );
      }

      const isRelativeImport =
        importPath.startsWith("./") || importPath.startsWith("../");

      // For relative imports, we first resolve the import path into a direct
      // import, as solc would do.
      //
      // We also need to validate that it doesn't abuse the import path syntax.
      if (isRelativeImport) {
        directImport = sourceNamePathJoin(
          path.dirname(from.sourceName),
          importPath,
        );

        // We also check that resolving the import paths into direct imports
        // doesn't result in accessing a file outside of the npm package/project
        if (from.type === ResolvedFileType.NPM_PACKAGE_FILE) {
          if (!directImport.startsWith(from.package.rootSourceName)) {
            throw new HardhatError(
              HardhatError.ERRORS.CORE.SOLIDITY.ILLEGAL_PACKAGE_IMPORT,
              {
                importPath,
                from: shortenPath(from.fsPath),
              },
            );
          }
        } else {
          if (directImport.startsWith("../")) {
            throw new HardhatError(
              HardhatError.ERRORS.CORE.SOLIDITY.ILEGALL_PROJECT_IMPORT,
              {
                importPath,
                from: shortenPath(from.fsPath),
              },
            );
          }
        }
      }

      const fromNpmPackage =
        from.type === ResolvedFileType.NPM_PACKAGE_FILE
          ? from.package
          : this.#npmPackageMap.hardhatProjectPackage;

      // While the remappings get presedence over local imports, we need
      // to compute if an import could have been considered local before
      // applying the remappings, as it can affect how they are applied.
      //
      // There are two cases in which an import is considered local:
      //  - If it's a relative import
      //  - If it's a direct import and isLocalDirectImport evaluates to true

      const isDirectImportFromPackageRoot =
        !isRelativeImport &&
        (await isLocalDirectImport(fromNpmPackage.rootFsPath, directImport));

      const isLocalImport = isRelativeImport || isDirectImportFromPackageRoot;

      // Now, we get the user remappings for the package/project, and select
      // the best user remapping. If there's any, we prioritize that.
      const packageUserRemappigns =
        this.#npmPackageMap.getUserRemappings(fromNpmPackage);

      const bestUserRemapping = selectBestRemapping(
        from.sourceName,
        directImport,
        packageUserRemappigns,
      );

      if (bestUserRemapping !== undefined) {
        const remappedDirectImport = applyValidRemapping(
          directImport,
          bestUserRemapping,
        );

        // Resolve based on the remappings
        return this.#newResolveUserRemappedImport({
          from,
          importPath,
          directImport,
          remappedDirectImport,
          remapping: bestUserRemapping,
          isLocalImport,
        });
      }

      // After user remappings, local imports take presedence

      if (isLocalImport) {
        return this.#newResolveLocalImport({
          from,
          importPath,
          directImport,
          isRelativeImport,
        });
      }

      return this.#newResolveImportThroughNpm({
        from,
        importPath,
        directImport,
      });
    });
  }

  async #newResolveUserRemappedImport({
    from,
    importPath,
    directImport,
    remappedDirectImport,
    remapping,
    isLocalImport,
  }: {
    from: ResolvedFile;
    importPath: string;
    directImport: string;
    isLocalImport: boolean;
    remappedDirectImport: string;
    remapping: ResolvedUserRemapping;
  }): Promise<
    Result<ResolvedFile, ImportDoesntExistError | ImportInvalidCasingError>
  > {
    const sourceName = remappedDirectImport;
    const existing = this.#resolvedFileBySourceName.get(remappedDirectImport);
    if (existing !== undefined) {
      return { success: true, value: existing };
    }

    const fromNpmPackage =
      from.type === ResolvedFileType.NPM_PACKAGE_FILE
        ? from.package
        : this.#npmPackageMap.hardhatProjectPackage;

    // We get the npm package that's the target of the remapping. If none
    // is present, that's because it's remapping to a local file, so it's
    // the fromNpmPackage.
    const targetNpmPackage =
      remapping.targetNpmPackage?.package ?? fromNpmPackage;

    // We get the relative path from the root, normally referred to as
    // `subpath` in npm land.
    // We create the source names using this pre-package.exports resolution
    // subpath.
    const subpath = path.relative(targetNpmPackage.rootSourceName, sourceName);

    // We apply the package.exports resolution in every case, except
    // when a package is importing itself with a direct import.
    // E.g. `import "contracts/File.sol";`
    //
    // We don't do that, because if you were in that same package, that would
    // be considered a local import and package.exports would be ignored.
    //
    // We want to match that behavior here.
    const applyPackageExportsResolution =
      targetNpmPackage.exports !== undefined &&
      (targetNpmPackage !== fromNpmPackage || !isLocalImport);

    const resolvedSubpath = applyPackageExportsResolution
      ? resolveSubpathWithPackageExports(targetNpmPackage, subpath)
      : subpath;

    const pathValidation = await validateFsPath(
      targetNpmPackage.rootFsPath,
      resolvedSubpath,
    );

    if (pathValidation.success === false) {
      if (pathValidation.error.type === "DOESNT_EXIST") {
        return {
          success: false,
          error: {
            type: "IMPORT_DOESNT_EXIST",
            fromFsPath: from.fsPath,
            importPath,
            userRemapping: {
              originalUserRemapping: remapping.originalFormat,
              actualUserRemapping: formatRemapping(remapping),
              remappingSource: remapping.source,
            },
            target: {
              npmPackage:
                targetNpmPackage !== this.#npmPackageMap.hardhatProjectPackage
                  ? targetNpmPackage
                  : undefined,
              subpath,
              resolvedSubpath: applyPackageExportsResolution
                ? resolvedSubpath
                : undefined,
            },
          },
        };
      }

      return {
        success: false,
        error: {
          type: "IMPORT_INVALID_CASING",
          fromFsPath: from.fsPath,
          importPath,
          userRemapping: {
            originalUserRemapping: remapping.originalFormat,
            actualUserRemapping: formatRemapping(remapping),
            remappingSource: remapping.source,
          },
          target: {
            npmPackage:
              targetNpmPackage !== this.#npmPackageMap.hardhatProjectPackage
                ? targetNpmPackage
                : undefined,
            subpath,
            resolvedSubpath: applyPackageExportsResolution
              ? resolvedSubpath
              : undefined,
          },
          correctCasing: pathValidation.error.correctCasing,
        },
      };
    }

    const fsPath = path.join(targetNpmPackage.rootFsPath, resolvedSubpath);

    const resolvedFile = await this.#buildResolvedFile(
      sourceName,
      fsPath,
      targetNpmPackage,
    );

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return { success: true, value: resolvedFile };
  }

  async #newResolveLocalImport({
    from,
    importPath,
    directImport,
    isRelativeImport,
  }: {
    from: ResolvedFile;
    importPath: string;
    directImport: string;
    isRelativeImport: boolean;
  }): Promise<
    Result<
      { file: ResolvedFile; generatedRemapping?: Remapping },
      ImportDoesntExistError | ImportInvalidCasingError
    >
  > {
    const fromNpmPackage =
      from.type === ResolvedFileType.NPM_PACKAGE_FILE
        ? from.package
        : this.#npmPackageMap.hardhatProjectPackage;

    const sourceName = isRelativeImport
      ? directImport
      : sourceNamePathJoin(fromNpmPackage.rootSourceName, directImport);

    const generatedRemapping: Remapping | undefined = isRelativeImport
      ? undefined
      : this.#npmPackageMap.generateRemappingForLocalDirectImport(
          fromNpmPackage,
          directImport,
        );

    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      return { success: true, value: { file: existing, generatedRemapping } };
    }

    const fsPath = sourceNamePathToFsPath(sourceName);
    const relativeFsPath = path.relative(fromNpmPackage.rootFsPath, fsPath);

    const pathValidation = await validateFsPath(
      fromNpmPackage.rootFsPath,
      relativeFsPath,
    );

    if (pathValidation.success === false) {
      if (pathValidation.error.type === "DOESNT_EXIST") {
        return {
          success: false,
          error: {
            type: "IMPORT_DOESNT_EXIST",
            fromFsPath: from.fsPath,
            importPath,
            target: {
              npmPackage:
                fromNpmPackage !== this.#npmPackageMap.hardhatProjectPackage
                  ? fromNpmPackage
                  : undefined,
              subpath: relativeFsPath,
            },
          },
        };
      }

      if (pathValidation.error.type === "CASING_ERROR") {
        return {
          success: false,
          error: {
            type: "IMPORT_INVALID_CASING",
            fromFsPath: from.fsPath,
            importPath,
            target: {
              npmPackage:
                fromNpmPackage !== this.#npmPackageMap.hardhatProjectPackage
                  ? fromNpmPackage
                  : undefined,
              subpath: relativeFsPath,
            },
            correctCasing: pathValidation.error.correctCasing,
          },
        };
      }
    }

    const resolvedFile = await this.#buildResolvedFile(
      sourceName,
      fsPath,
      fromNpmPackage,
    );

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return { success: true, value: { file: resolvedFile, generatedRemapping } };
  }

  async #newResolveImportThroughNpm({
    from,
    importPath,
    directImport,
  }: {
    from: ResolvedFile;
    importPath: string;
    directImport: string;
  }): Promise<
    Result<
      { file: ResolvedFile; generatedRemapping?: Remapping },
      | ImportDoesntExistError
      | ImportInvalidCasingError
      | ImportWithInvalidNpmSyntaxError
      | ImportOfUninstalledPackageError
      | ImportOfNpmPackageWithRemappingErrorsError
    >
  > {
    const parsedDirectImport = parseNpmDirectImport(directImport);

    if (parsedDirectImport === undefined) {
      return {
        success: false,
        error: {
          type: "IMPORT_WITH_INVALID_NPM_SYNTAX",
          fromFsPath: from.fsPath,
          importPath,
        },
      };
    }

    const fromNpmPackage =
      from.type === ResolvedFileType.NPM_PACKAGE_FILE
        ? from.package
        : this.#npmPackageMap.hardhatProjectPackage;

    const installationName = parsedDirectImport.package;

    const dependencyResolution =
      await this.#npmPackageMap.resolveDependencyByInstallationName(
        fromNpmPackage,
        installationName,
      );

    if (dependencyResolution === undefined) {
      return {
        success: false,
        error: {
          type: "IMPORT_OF_UNINSTALLED_PACKAGE",
          fromFsPath: from.fsPath,
          importPath,
          packageName: parsedDirectImport.package,
        },
      };
    }

    if (dependencyResolution.remappingErrros !== undefined) {
      return {
        success: false,
        error: {
          type: "IMPORT_OF_NPM_PACKAGE_WITH_REMAPPING_ERRORS",
          fromFsPath: from.fsPath,
          importPath,
          packageName: parsedDirectImport.package,
          remappingErrors: dependencyResolution.remappingErrros,
        },
      };
    }

    const dependency = dependencyResolution.package;

    const sourceName = sourceNamePathJoin(
      dependency.rootSourceName,
      parsedDirectImport.subpath,
    );

    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      return {
        success: true,
        value: {
          file: existing,
          generatedRemapping: dependencyResolution.generatedRemapping,
        },
      };
    }

    const subpath = parsedDirectImport.subpath;

    // We use the subpath (pre-resolution) to create source names
    const resolvedSubpath = resolveSubpathWithPackageExports(
      dependency,
      parsedDirectImport.subpath,
    );

    const pathValidation = await validateFsPath(
      dependency.rootFsPath,
      resolvedSubpath,
    );

    if (pathValidation.success === false) {
      if (pathValidation.error.type === "DOESNT_EXIST") {
        return {
          success: false,
          error: {
            type: "IMPORT_DOESNT_EXIST",
            fromFsPath: from.fsPath,
            importPath,
            target: {
              npmPackage:
                dependency !== this.#npmPackageMap.hardhatProjectPackage
                  ? dependency
                  : undefined,
              subpath,
              resolvedSubpath:
                dependency.exports !== undefined ? resolvedSubpath : undefined,
            },
          },
        };
      }

      return {
        success: false,
        error: {
          type: "IMPORT_INVALID_CASING",
          fromFsPath: from.fsPath,
          importPath,
          target: {
            npmPackage:
              dependency !== this.#npmPackageMap.hardhatProjectPackage
                ? dependency
                : undefined,
            subpath,
            resolvedSubpath:
              dependency.exports !== undefined ? resolvedSubpath : undefined,
          },
          correctCasing: pathValidation.error.correctCasing,
        },
      };
    }

    const fsPath = path.join(dependency.rootFsPath, resolvedSubpath);

    const resolvedFile = await this.#buildResolvedFile(
      sourceName,
      fsPath,
      dependency,
    );

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return {
      success: true,
      value: {
        file: resolvedFile,
        generatedRemapping: dependencyResolution.generatedRemapping,
      },
    };
  }

  async #buildResolvedFile(
    sourceName: string,
    fsPath: string,
    npmPackage: ResolvedNpmPackage,
  ): Promise<ResolvedFile> {
    const content = await readFileContent(fsPath);
    if (npmPackage === this.#npmPackageMap.hardhatProjectPackage) {
      return new ProjectResolvedFileImplementation({
        sourceName,
        fsPath,
        content,
      });
    }

    return new NpmPackageResolvedFileImplementation({
      sourceName,
      fsPath,
      content: await readFileContent(fsPath),
      package: npmPackage,
    });
  }

  public getRemappings(): Remapping[] {
    const remappings: Remapping[] = this.#npmPackageMap.getLegacyRemappings();

    // TODO: Always order this in a consistent way
    for (const [packageSourceName, prefixes] of this.#localPrefixesByPackage) {
      for (const prefix of prefixes) {
        remappings.push({
          context: packageSourceName.rootSourceName,
          prefix,
          target: packageSourceName.rootSourceName + prefix,
        });
      }
    }

    // We sort the remappings acording to the remappings selection rules, plus
    // the targets, which shouldn't be needed.
    remappings
      .sort((a, b) => a.target.localeCompare(b.target))
      .sort((a, b) => a.target.length - b.target.length)
      .sort((a, b) => a.prefix.localeCompare(b.prefix))
      .sort((a, b) => a.prefix.length - b.prefix.length)
      .sort((a, b) => a.context.localeCompare(b.context))
      .sort((a, b) => a.context.length - b.context.length);

    return remappings;
  }

  // >>>>>>>>>> BEGIN SECTION: Import resolution selection
  //
  // The private methods in this section are in charge of selecting which import
  // resolution technique to use, but they don't create any ResolvedFile.
  //
  // These techniques are:
  //  1. Resolving an import to a project file
  //  2. Resolving an import remapped by the user into an npm package
  //  3. Resolving an import from an npm package to one of its own files with a
  //     relative import
  //  4. Resolving an import from an npm package to one of its own files with a
  //     direct import — This case is different from 3, as without especial care
  //     it could be affected by one of the user remappings.
  //  5. Resolving an import to a different npm package using our own remappings

  /**
   * Resolves an import from a project file.
   *
   * This method applies the user remappings, if necessary, and uses the
   * appropriate resolution technique.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths,
   * but before applying any remapping.
   */
  async #resolveImportFromProjectFile({
    from,
    importPath,
    directImport,
  }: {
    from: ProjectResolvedFile;
    directImport: string;
    importPath: string;
  }): Promise<ResolvedFile> {
    const hardhatProjectNpmPackage =
      this.#npmPackageMap.getHardhatProjectPackage();

    const remappings = this.#npmPackageMap.getUserRemappings(
      hardhatProjectNpmPackage,
    );

    const bestUserRemapping = selectBestRemapping(
      from.sourceName,
      directImport,
      remappings,
    );

    if (bestUserRemapping !== undefined) {
      return this.#resolveUserRemappedImportFromProjectFile({
        from,
        importPath,
        directImport,
        remapping: bestUserRemapping,
      });
    }

    if (await isLocalDirectImport(this.#projectRoot, directImport)) {
      return this.#resolveImportToProjectFile({
        from,
        importPath,
        fsPathWithinTheProject: sourceNamePathToFsPath(directImport),
      });
    }

    return this.#resolveImportThroughNpm({
      from,
      importPath,
      directImport,
    });
  }

  /**
   * Resolves an import from a project file that is affected by a user
   * remapping.
   *
   * Note that this method must only be called with the best user remapping
   * applicable to the import, as defined by solc. Otherwise, it's behavior will
   * be misleading.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths,
   * but before applying any remapping.
   * @param remapping The user remapping that will be applied.
   */
  async #resolveUserRemappedImportFromProjectFile({
    from,
    importPath,
    directImport,
    remapping,
  }: {
    from: ProjectResolvedFile;
    importPath: string;
    directImport: string;
    remapping: ResolvedUserRemapping;
  }): Promise<ResolvedFile> {
    const remappedDirectImport = applyValidRemapping(directImport, remapping);

    // Special case, where a user remapping's target is an npm pacakge
    if (remapping.targetNpmPackage !== undefined) {
      return this.#resolveImportToNpmPackageRemappedByUser({
        from,
        importPath,
        directImport: remappedDirectImport,
        remapping: {
          // This weird syntax is because TS doesn't realize that
          // bestUserRemapping is Required<ResolvedUserRemapping> here
          ...remapping,
          targetNpmPackage: remapping.targetNpmPackage,
        },
      });
    }

    // Otherwise, the file should be a local file included in the project
    if (remappedDirectImport.startsWith("../")) {
      throw new HardhatError(
        HardhatError.ERRORS.CORE.SOLIDITY.ILLEGAL_PROJECT_IMPORT_AFTER_REMAPPING,
        {
          importPath,
          from: shortenPath(from.fsPath),
          remapping: remapping.originalFormat,
          remappedDirectImport,
        },
      );
    }

    return this.#resolveImportToProjectFile({
      from,
      importPath,
      fsPathWithinTheProject: sourceNamePathToFsPath(remappedDirectImport),
    });
  }

  /**
   * Resolves an import from an npm file.
   *
   * This method does not apply any remapping that may be present in the npm
   * package.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths,
   * but without applying any remapping.
   */
  async #resolveImportFromNpmPackageFile({
    from,
    importPath,
    directImport,
  }: {
    from: NpmPackageResolvedFile;
    directImport: string;
    importPath: string;
  }): Promise<ResolvedFile> {
    // If we wanted to apply its own remappings, this would be the place.
    // Initially we won't support it.
    if (directImport.startsWith(from.package.rootSourceName)) {
      return this.#resolveRelativeImportFromNpmPackage({
        from,
        importPath,
        directImport,
      });
    }

    // This was already a direct import, and may be to the same package.
    // As we allow this imports in the local project files, we should also allow
    // them on npm packages. If we don't projects won't be easily distributable
    // through npm, even if they don't use remappings.
    if (await isLocalDirectImport(from.package.rootFsPath, directImport)) {
      const resolvedFile = await this.#resolveLocalImportFromNpmPackage({
        from,
        importPath,
        directImport,
      });

      let prefixesNeededByPackage = this.#localPrefixesByPackage.get(
        from.package,
      );

      if (prefixesNeededByPackage === undefined) {
        prefixesNeededByPackage = new Set();
        this.#localPrefixesByPackage.set(from.package, prefixesNeededByPackage);
      }

      prefixesNeededByPackage.add(
        getDirectImportLocalDesambiguationPrefix(directImport),
      );

      return resolvedFile;
    }

    return this.#resolveImportThroughNpm({
      from,
      importPath,
      directImport,
    });
  }

  /**
   * This method resolves an import that has to go through the npm resolution
   * process and selects the appropriate technique to resolve it.
   *
   * This method does not apply nor define any remapping, but it populates the
   * `#dependencyMaps` with dependencies that each package uses, so that we can
   * create all the necessary remappings at the end of the resolution process.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths,
   * but without applying any remapping.
   */
  async #resolveImportThroughNpm({
    from,
    importPath,
    directImport,
  }: {
    from: ResolvedFile;
    importPath: string;
    directImport: string;
  }): Promise<ResolvedFile> {
    const parsedDirectImport = parseNpmDirectImport(directImport);

    if (parsedDirectImport === undefined) {
      throw new HardhatError(
        HardhatError.ERRORS.CORE.SOLIDITY.INVALID_NPM_IMPORT,
        {
          importPath,
          from: shortenPath(from.fsPath),
        },
      );
    }

    const dependency = await this.#resolveNpmPackageForImport({
      from,
      importPath,
      importPackageName: parsedDirectImport.package,
    });

    if (dependency === this.#npmPackageMap.getHardhatProjectPackage()) {
      return this.#resolveImportToProjectFile({
        from,
        importPath,
        // If we import a file through npm and end up in the Hardhat project,
        // we are going to remap the importPackageName to "", so that the path
        // section of the parsed direct import should be the relative path.
        fsPathWithinTheProject: sourceNamePathToFsPath(
          parsedDirectImport.subpath,
        ),
      });
    }

    return this.#resolveImportToNpmPackage({
      from,
      importPath,
      importedPackage: dependency,
      subpath: parsedDirectImport.subpath,
    });
  }

  // >>>>>>>>>> END SECTION: Import resolution selection

  // >>>>>>>>>> BEGIN SECTION: Import resolution techniques
  //
  // The private methods in this section implement the different import
  // import resolution techniques, which have been explained in the previous
  // section.

  /**
   * This method implements the import resolution technique number 1: Importing
   * a file that is within the project. Note that this method applies both to
   * imports from project files as well as imports from npm packages that may
   * have the project as a dependency.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param pathWithinTheProject The path within the project to import, after
   * normalizing relative paths, applying user remappings and/or stripping the
   * npm package name.
   */
  async #resolveImportToProjectFile({
    from,
    importPath,
    fsPathWithinTheProject,
  }: {
    from: ResolvedFile;
    importPath: string;
    fsPathWithinTheProject: string;
  }): Promise<ProjectResolvedFile> {
    const sourceName = fsPathToSourceNamePath(fsPathWithinTheProject);
    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions --
      The cache is type-unsafe, but we are sure this is a ProjectResolvedFile */
      return existing as ProjectResolvedFile;
    }

    // This is a project file, so if it was imported from a local file, this
    // is the direct import, without any remapping or necessary consideration.
    // If this was imported from an npm package, we are remapping the package
    // name of the import to "", so that the direct import is also the same as
    // the relative path.
    await this.#validateExistanceAndCasingOfImport({
      from,
      importPath,
      relativeFsPathToValidate: fsPathWithinTheProject,
      absoluteFsPathToValidateFrom: this.#projectRoot,
    });

    const fsPath = path.join(this.#projectRoot, fsPathWithinTheProject);

    const resolvedFile: ProjectResolvedFile =
      new ProjectResolvedFileImplementation({
        sourceName,
        fsPath,
        content: await readFileContent(fsPath),
      });

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return resolvedFile;
  }

  /**
   * This method implements the import resolution technique number 2: A project
   * file has an import that should be resolved to a file in an npm package due
   * to a user remapping.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths,
   * and applying the user remapping.
   * @param remapping The remapping that was applied.
   */
  async #resolveImportToNpmPackageRemappedByUser({
    from,
    importPath,
    directImport,
    remapping,
  }: {
    from: ProjectResolvedFile;
    importPath: string;
    directImport: string;
    remapping: Required<ResolvedUserRemapping>;
  }): Promise<NpmPackageResolvedFile> {
    const sourceName = directImport;
    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions --
      The cache is type-unsafe, but we are sure this is a NpmPackageResolvedFile */
      return existing as NpmPackageResolvedFile;
    }

    const subpath = path.relative(
      remapping.targetNpmPackage.package.rootSourceName,
      directImport,
    );
    const resolvedSubpath = resolveSubpathWithPackageExports(
      remapping.targetNpmPackage.package,
      subpath,
    );

    // We don't add the dependency to `this.#dependencyMaps` because we
    // don't need a new remapping for this package, as it's already
    // remapped by the user.

    await this.#validateExistanceAndCasingOfImport({
      from,
      importPath,
      relativeFsPathToValidate: sourceNamePathToFsPath(resolvedSubpath),
      absoluteFsPathToValidateFrom:
        remapping.targetNpmPackage.package.rootFsPath,
      usingPackageExports:
        remapping.targetNpmPackage.package.exports !== undefined,
    });

    const fsPath = path.join(
      remapping.targetNpmPackage.package.rootFsPath,
      resolvedSubpath,
    );

    const resolvedFile: NpmPackageResolvedFile =
      new NpmPackageResolvedFileImplementation({
        sourceName,
        fsPath,
        content: await readFileContent(fsPath),
        package: remapping.targetNpmPackage.package,
      });

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return resolvedFile;
  }

  /**
   * This method implements the import resolution technique number 3: A file
   * from an npm package is importing another file from the same package with a
   * relative import.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths.
   * It must start with the package's root source name.
   */
  async #resolveRelativeImportFromNpmPackage({
    from,
    importPath,
    directImport,
  }: {
    from: NpmPackageResolvedFile;
    directImport: string;
    importPath: string;
  }): Promise<NpmPackageResolvedFile> {
    const sourceName = directImport;
    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions --
      The cache is type-unsafe, but we are sure this is a NpmPackageResolvedFile */
      return existing as NpmPackageResolvedFile;
    }

    const relativePath = sourceNamePathToFsPath(
      path.relative(from.package.rootSourceName, directImport),
    );

    await this.#validateExistanceAndCasingOfImport({
      from,
      importPath,
      relativeFsPathToValidate: relativePath,
      absoluteFsPathToValidateFrom: from.package.rootFsPath,
    });

    const filePath = path.join(from.package.rootFsPath, relativePath);

    const resolvedFile: NpmPackageResolvedFile =
      new NpmPackageResolvedFileImplementation({
        sourceName,
        fsPath: filePath,
        content: await readFileContent(filePath),
        package: from.package,
      });

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return resolvedFile;
  }

  /**
   * This method implements the import resolution technique number 4: A file
   * from an npm package is importing another file from the same package with a
   * direct import.
   *
   * For example, a file `node_modules/foo/File.sol` imports
   * `node_modules/foo/bar/File2.sol` with the direct import `bar/File2.sol`.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param directImport The direct import path, after resolving relative paths.
   * The direct import must be considered local within the package, according to
   * the rules of the `#isDirectImportLocal` method.
   */
  async #resolveLocalImportFromNpmPackage({
    from,
    importPath,
    directImport,
  }: {
    from: NpmPackageResolvedFile;
    directImport: string;
    importPath: string;
  }): Promise<NpmPackageResolvedFile> {
    const sourceName = from.package.rootSourceName + "/" + directImport;
    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions --
      The cache is type-unsafe, but we are sure this is a NpmPackageResolvedFile */
      return existing as NpmPackageResolvedFile;
    }

    const relativeFsPath = sourceNamePathToFsPath(directImport);

    await this.#validateExistanceAndCasingOfImport({
      from,
      importPath,
      relativeFsPathToValidate: relativeFsPath,
      absoluteFsPathToValidateFrom: from.package.rootFsPath,
    });

    const fsPath = path.join(from.package.rootFsPath, relativeFsPath);

    const resolvedFile: NpmPackageResolvedFile =
      new NpmPackageResolvedFileImplementation({
        sourceName,
        fsPath,
        content: await readFileContent(fsPath),
        package: from.package,
      });

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return resolvedFile;
  }

  /**
   * This method implements the import resolution technique number 5: A file,
   * within the project or from an npm pacakge, is importing a file from a
   * different npm package.
   *
   * Note: This is not meant to support imports into the Hardhat project.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param importedPackage The NpmPackage that is being imported.
   * @param subpath The path to the file to import, within the
   * package. That means, after parsing the direct import, and stripping the
   * package part, before resolving package exports.
   */
  async #resolveImportToNpmPackage({
    from,
    importPath,
    importedPackage,
    subpath,
  }: {
    from: ResolvedFile;
    importPath: string;
    importedPackage: ResolvedNpmPackage;
    subpath: string;
  }): Promise<NpmPackageResolvedFile> {
    const sourceName = importedPackage.rootSourceName + "/" + subpath;

    const existing = this.#resolvedFileBySourceName.get(sourceName);
    if (existing !== undefined) {
      /* eslint-disable-next-line @typescript-eslint/consistent-type-assertions --
      The cache is type-unsafe, but we are sure this is a NpmPackageResolvedFile */
      return existing as NpmPackageResolvedFile;
    }

    // We use the subpath (pre-resolution) to create source names
    const resolvedSubpath = resolveSubpathWithPackageExports(
      importedPackage,
      subpath,
    );

    await this.#validateExistanceAndCasingOfImport({
      from,
      importPath,
      relativeFsPathToValidate: sourceNamePathToFsPath(resolvedSubpath),
      absoluteFsPathToValidateFrom: importedPackage.rootFsPath,
      usingPackageExports: importedPackage.exports !== undefined,
    });

    const fsPath = path.join(importedPackage.rootFsPath, resolvedSubpath);

    const resolvedFile: NpmPackageResolvedFile =
      new NpmPackageResolvedFileImplementation({
        sourceName,
        fsPath,
        content: await readFileContent(fsPath),
        package: importedPackage,
      });

    this.#resolvedFileBySourceName.set(sourceName, resolvedFile);

    return resolvedFile;
  }

  // >>>>>>>>>> END SECTION: Import resolution techniques

  /**
   * Resolves an npm package as a dependency of another one.
   *
   * @param from The package to resolve the dependency from.
   * @param installationName The installation name of the package that should be
   * resolved as a dependency.
   * @returns A ResolvedNpmPackage or PROJECT_ROOT_SENTINEL.
   */
  async #resolveNpmPackage({
    from,
    installationName,
  }: {
    from: ResolvedNpmPackage;
    installationName: string;
  }): Promise<ResolvedNpmPackage> {
    const result =
      await this.#npmPackageMap.resolveDependencyByInstallationName(
        from,
        installationName,
      );

    if (result === undefined) {
      throw new HardhatError(
        HardhatError.ERRORS.CORE.SOLIDITY.NPM_DEPEDNDENCY_NOT_INSTALLED,
        {
          from:
            from === this.#npmPackageMap.getHardhatProjectPackage()
              ? "your project"
              : `"${shortenPath(from.rootFsPath)}"`,
          packageName: installationName,
        },
      );
    }

    if (result.remappingErrros !== undefined) {
      throw new Error(
        "TODO: Remapping errors while resolving an npm package: " +
          JSON.stringify(result.remappingErrros, null, 2),
      );
    }

    return result.dependency;
  }

  /**
   * Resolves the npm package imported by the importPath in the from file.
   *
   * @param from The file from which the import is being resolved.
   * @param importPath The import path, as written in the source code.
   * @param importPackageName The name of the package to import, as present in
   * the importPath, and not necessarily the name of the package in the
   * package.json.
   * @returns A ResolvedNpmPackage or PROJECT_ROOT_SENTINEL.
   */
  async #resolveNpmPackageForImport({
    from,
    importPath,
    importPackageName,
  }: {
    from: ResolvedFile;
    importPath: string;
    importPackageName: string;
  }): Promise<ResolvedNpmPackage> {
    try {
      return await this.#resolveNpmPackage({
        from:
          from.type === ResolvedFileType.PROJECT_FILE
            ? this.#npmPackageMap.getHardhatProjectPackage()
            : from.package,
        installationName: importPackageName,
      });
    } catch (error) {
      ensureError(error);

      if (
        HardhatError.isHardhatError(
          error,
          HardhatError.ERRORS.CORE.SOLIDITY.NPM_DEPEDNDENCY_NOT_INSTALLED,
        )
      ) {
        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.IMPORTED_NPM_DEPENDENCY_NOT_INSTALLED,
          {
            from: shortenPath(from.fsPath),
            importPath,
          },
          error,
        );
      }

      throw error;
    }
  }

  /**
   * This is an utility method that validates the existance and casing of an
   * imported file as part of the different resolution techniques.
   *
   * `from` and `importPath` are used to provide a user-friendly error message,
   * but the actual validation is done using `relativePathToValidate` and
   * `absolutePathToValidateFrom`.
   *
   * @param from The file with the import.
   * @param importPath The import path, as written in the source code.
   * @param relativePathToValidate The relative path to validate its existance.
   * @param absolutePathToValidateFrom The absolute path from in which the
   * relative path is.
   * @param usingPackageExports Whether the import is using package exports,
   * which controls which kind of error is thrown.
   */
  async #validateExistanceAndCasingOfImport({
    from,
    importPath,
    relativeFsPathToValidate,
    absoluteFsPathToValidateFrom,
    usingPackageExports,
  }: {
    from: ResolvedFile;
    importPath: string;
    relativeFsPathToValidate: string;
    absoluteFsPathToValidateFrom: string;
    usingPackageExports?: boolean;
  }) {
    let trueCaseFsPath: string;
    try {
      trueCaseFsPath = await getFileTrueCase(
        absoluteFsPathToValidateFrom,
        relativeFsPathToValidate,
      );
    } catch (error) {
      ensureError(error, FileNotFoundError);

      throw new HardhatError(
        HardhatError.ERRORS.CORE.SOLIDITY.IMPORTED_FILE_DOESNT_EXIST,
        { importPath, from: shortenPath(from.fsPath) },
        error,
      );
    }

    if (relativeFsPathToValidate !== trueCaseFsPath) {
      // If we are using package exports, we need to throw a special error,
      // as we can't compute the correct casing.
      if (usingPackageExports === true) {
        throw new HardhatError(
          HardhatError.ERRORS.CORE.SOLIDITY.IMPORTED_PACKAGE_EXPORTS_FILE_WITH_INCORRECT_CASING,
          {
            importPath,
            from: shortenPath(from.fsPath),
          },
        );
      }

      throw new HardhatError(
        HardhatError.ERRORS.CORE.SOLIDITY.IMPORTED_FILE_WITH_INCORRECT_CASING,
        {
          importPath,
          from: shortenPath(from.fsPath),
          correctCasing: fsPathToSourceNamePath(trueCaseFsPath),
        },
      );
    }
  }
}

/**
 * Reads and analyzes the file at the given absolute path.
 */
async function readFileContent(absolutePath: string): Promise<FileContent> {
  const text = await readUtf8File(absolutePath);
  const { imports, versionPragmas } = analyze(text);

  return {
    text,
    importPaths: imports,
    versionPragmas,
  };
}

/**
 * Resolves a subpath for a given package, when it uses package#exports
 * @param npmPackage
 * @param subpath
 * @returns
 */
function resolveSubpathWithPackageExports(
  npmPackage: ResolvedNpmPackage,
  subpath: string,
): string {
  if (npmPackage.exports === undefined) {
    return subpath;
  }
  try {
    // As we are resolving Solidity files, the conditions don't really apply,
    // and Solidity package authors don't use them either.
    //
    // We use `resolve.exports` with the appropiate options so that it only
    // takes the `"default"` condition into account.
    const resolveOutput = resolve.exports(npmPackage, subpath, {
      browser: false,
      conditions: [],
      require: false,
      unsafe: true,
    });

    assertHardhatInvariant(
      resolveOutput !== undefined,
      "resolve.exports should always return a result when package.exports exist",
    );

    const resolvedSubpath = resolveOutput[0].slice(2); // skip the leading './'

    return resolvedSubpath.replace(/\/|\\/g, path.sep); // use fs path separator
  } catch (error) {
    ensureError(error, Error);

    throw new HardhatError(
      HardhatError.ERRORS.CORE.SOLIDITY.RESOLVE_NOT_EXPORTED_NPM_FILE,
      { module: `${npmPackage.name}/${subpath}` },
      error,
    );
  }
}

async function validateFsPath(
  from: string,
  relative: string,
): Promise<
  Result<
    undefined,
    { type: "DOESNT_EXIST" } | { type: "CASING_ERROR"; correctCasing: string }
  >
> {
  let trueCaseFsPath: string;
  try {
    trueCaseFsPath = await getFileTrueCase(from, relative);
  } catch (error) {
    ensureError(error, FileNotFoundError);

    return { success: false, error: { type: "DOESNT_EXIST" } };
  }

  if (relative !== trueCaseFsPath) {
    return {
      success: false,
      error: { type: "CASING_ERROR", correctCasing: trueCaseFsPath },
    };
  }

  return { success: true, value: undefined };
}
