// This file was autogenerated by Hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface C$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "C";
  readonly sourceName: "contracts/C.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea264697066735822122066220fc59f0e456bfeed804b45a091ea9b64289092ec824766fee8af886447de64736f6c63430008160033";
  readonly deployedBytecode: "0x60806040525f80fdfea264697066735822122066220fc59f0e456bfeed804b45a091ea9b64289092ec824766fee8af886447de64736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "contracts/C.sol";
  readonly buildInfoId: "652e717a54777ac28e86bc7084fcbc8f";
}

export interface C2$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "C2";
  readonly sourceName: "contracts/C.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea2646970667358221220c72aea65f1253bb034ad646e28ff9b53b7a7effdf03dfd58726d59b7083d8d9c64736f6c63430008160033";
  readonly deployedBytecode: "0x60806040525f80fdfea2646970667358221220c72aea65f1253bb034ad646e28ff9b53b7a7effdf03dfd58726d59b7083d8d9c64736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "contracts/C.sol";
  readonly buildInfoId: "652e717a54777ac28e86bc7084fcbc8f";
}

import "@ignored/hardhat-vnext/types/artifacts";
declare module "@ignored/hardhat-vnext/types/artifacts" {
  interface ArtifactMap {
    ["C"]: C$Type;
    ["C2"]: C2$Type;
    ["contracts/C.sol:C"]: C$Type;
    ["contracts/C.sol:C2"]: C2$Type;
  }
}
