// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { A$Type } from "./A";
import { B$Type } from "./B";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["A"]: A$Type;
    ["B"]: B$Type;
    ["contracts/A.sol:A"]: A$Type;
    ["contracts/A.sol:B"]: B$Type;
  }
}
