// This file was autogenerated by Hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface B$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "B";
  readonly sourceName: "contracts/B.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f80fd5b50603e80601a5f395ff3fe60806040525f80fdfea26469706673582212203a770298304d45a01cb3629a2f032da51fb0fe9d9c0b8148d8aa64f0dd779c8564736f6c63430008160033";
  readonly deployedBytecode: "0x60806040525f80fdfea26469706673582212203a770298304d45a01cb3629a2f032da51fb0fe9d9c0b8148d8aa64f0dd779c8564736f6c63430008160033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "contracts/B.sol";
  readonly buildInfoId: "652e717a54777ac28e86bc7084fcbc8f";
};

import "@ignored/hardhat-vnext/types/artifacts";
declare module "@ignored/hardhat-vnext/types/artifacts" {
  interface ArtifactMap {
    ["B"]: B$Type;
    ["contracts/B.sol:B"]: B$Type;
  }
}