// This file was autogenerated by Hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface NoImports$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "NoImports";
  readonly sourceName: "contracts/NoImports.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220622ff1f92fb75a340477cc69a6f9fcbbd9518f40d01c4ed0fc96c42f94e05c5a64736f6c63430007010033";
  readonly deployedBytecode: "0x6080604052600080fdfea2646970667358221220622ff1f92fb75a340477cc69a6f9fcbbd9518f40d01c4ed0fc96c42f94e05c5a64736f6c63430007010033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "contracts/NoImports.sol";
  readonly buildInfoId: "89eed7b31e13eec3ee71467386d39108";
}

import "@ignored/hardhat-vnext/types/artifacts";
declare module "@ignored/hardhat-vnext/types/artifacts" {
  interface ArtifactMap {
    ["NoImports"]: NoImports$Type;
    ["contracts/NoImports.sol:NoImports"]: NoImports$Type;
  }
}
