// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    B: never;
  }

  interface Artifacts {
    readArtifact<ArgT extends keyof ArtifactsMap>(
      contractNameOrFullyQualifiedName: ArgT
    ): ArtifactsMap[ArgT];
    readArtifact(contractNameOrFullyQualifiedName: string): Artifact;

    readArtifactSync<ArgT extends keyof ArtifactsMap>(
      contractNameOrFullyQualifiedName: ArgT
    ): ArtifactsMap[ArgT];
    readArtifactSync(contractNameOrFullyQualifiedName: string): Artifact;
  }
}
