import { extendConfig, task } from "@nomiclabs/buidler/config";
import { NomicLabsBuidlerPluginError } from "@nomiclabs/buidler/plugins";
import { ActionType } from "@nomiclabs/buidler/types";
import SemverRange from "semver/classes/range";

import { defaultEtherscanConfig } from "./config";
import { pluginName } from "./pluginContext";

interface VerificationArgs {
  address: string;
  constructorArguments: string[];
  // Filename of constructor arguments module.
  constructorArgs?: string;
}

extendConfig(defaultEtherscanConfig);

const verify: ActionType<VerificationArgs> = async (
  {
    address,
    constructorArguments: constructorArgsList,
    constructorArgs: constructorArgsModule,
  },
  { config, network, run }
) => {
  const { etherscan } = config;

  if (etherscan.apiKey.trim() === "") {
    throw new NomicLabsBuidlerPluginError(
      pluginName,
      `Please provide an Etherscan API token via buidler config.
E.g.: { [...], etherscan: { apiKey: 'an API key' }, [...] }
See https://etherscan.io/apis`
    );
  }

  if (network.name === "buidlerevm") {
    throw new NomicLabsBuidlerPluginError(
      pluginName,
      `The selected network is ${network.name}. Please select a network supported by Etherscan.`
    );
  }

  const { isAddress } = await import("@ethersproject/address");
  if (!isAddress(address)) {
    throw new NomicLabsBuidlerPluginError(
      pluginName,
      `${address} is an invalid address.`
    );
  }

  const { getVersionNumber, inferSolcVersion, InferralType } = await import(
    "./solc/version"
  );
  const solcVersionConfig = getVersionNumber(config.solc.version);

  const supportedSolcVersionRange = new SemverRange(">=0.4.11");
  // Etherscan only supports solidity versions higher than or equal to v0.4.11.
  // See https://etherscan.io/solcversions
  // TODO: perhaps querying and scraping this list would be a better approach?
  // This list should be validated - it links to https://github.com/ethereum/solc-bin/blob/gh-pages/bin/list.txt
  // which has many old compilers included in the list too.
  if (!supportedSolcVersionRange.test(solcVersionConfig.toString())) {
    throw new NomicLabsBuidlerPluginError(
      pluginName,
      `Etherscan only supports compiler versions 0.4.11 and higher.
See https://etherscan.io/solcversions for more information.`
    );
  }

  let constructorArguments;
  if (typeof constructorArgsModule === "string") {
    try {
      constructorArguments = await import(constructorArgsModule);
      if (!Array.isArray(constructorArguments)) {
        throw new NomicLabsBuidlerPluginError(
          pluginName,
          `The module doesn't export a list. The module should look like this:
module.exports = [ arg1, arg2, ... ];`
        );
      }
    } catch (error) {
      throw new NomicLabsBuidlerPluginError(
        pluginName,
        "Importing the module for the constructor arguments list failed.",
        error
      );
    }
  } else {
    constructorArguments = constructorArgsList;
  }

  let etherscanAPIEndpoint: URL;
  const {
    getEtherscanEndpoint,
    retrieveContractBytecode,
    NetworkProberError,
  } = await import("./network/prober");
  try {
    etherscanAPIEndpoint = await getEtherscanEndpoint(network.provider);
  } catch (error) {
    if (error instanceof NetworkProberError) {
      throw new NomicLabsBuidlerPluginError(
        pluginName,
        `${error.message} The selected network is ${network.name}.
Common causes:
  - Wrong network selected
  - Faulty buidler network config`,
        error
      );
    }
    // Shouldn't be reachable.
    throw error;
  }

  const deployedContractBytecode = await retrieveContractBytecode(
    address,
    network.provider
  );
  if (deployedContractBytecode === null) {
    throw new NomicLabsBuidlerPluginError(
      pluginName,
      `The address ${address} has no bytecode. Is the contract deployed to this network?
The selected network is ${network.name}.`
    );
  }

  const bytecodeBuffer = Buffer.from(deployedContractBytecode, "hex");
  const solcVersionRange = await inferSolcVersion(bytecodeBuffer);

  if (!solcVersionRange.isIncluded(solcVersionConfig)) {
    let detailedContext;
    if (solcVersionRange.inferralType === InferralType.EXACT) {
      detailedContext = `The expected version is ${solcVersionRange}.`;
    } else {
      detailedContext = `The expected version range is ${solcVersionRange}.`;
    }
    const message = `The bytecode retrieved could not have been generated by the selected compiler.
The selected compiler version is v${config.solc.version}.
${detailedContext}
The selected network is ${network.name}.
Common causes:
  - Wrong compiler version in buidler config
  - Wrong address for contract
  - Wrong network selected or faulty buidler network config`;
    throw new NomicLabsBuidlerPluginError(pluginName, message);
  }

  const { lookupMatchingBytecode, compile } = await import("./solc/bytecode");
  // TODO: this gives us the input for all contracts.
  // This could be restricted to relevant contracts in a future iteration of the compiler tasks.
  const { compilerInput, compilerOutput } = await compile(run);

  const contractInformation = await lookupMatchingBytecode(
    compilerOutput.contracts,
    deployedContractBytecode,
    solcVersionRange.inferralType
  );
  if (contractInformation === null) {
    const message = `The contract was not found among the ones present in this project.
The selected network is ${network.name}.
Common causes:
  - Wrong address for contract
  - Wrong network selected or faulty buidler network config`;
    throw new NomicLabsBuidlerPluginError(pluginName, message);
  }

  const { encodeArguments } = await import("./ABIEncoder");
  const deployArgumentsEncoded = await encodeArguments(
    contractInformation.contract.abi,
    contractInformation.contractFilename,
    contractInformation.contractName,
    constructorArguments
  );

  // Ensure the linking information is present in the compiler input;
  compilerInput.settings.libraries = contractInformation.libraryLinks;
  const compilerInputJSON = JSON.stringify(compilerInput);

  const solcFullVersion = await solcVersionConfig.getLongVersion();

  const { toVerifyRequest, toCheckStatusRequest } = await import(
    "./etherscan/EtherscanVerifyContractRequest"
  );
  const request = toVerifyRequest({
    apiKey: etherscan.apiKey,
    contractAddress: address,
    sourceCode: compilerInputJSON,
    contractFilename: contractInformation.contractFilename,
    contractName: contractInformation.contractName,
    compilerVersion: solcFullVersion,
    constructorArguments: deployArgumentsEncoded,
  });

  const { getVerificationStatus, verifyContract, delay } = await import(
    "./etherscan/EtherscanService"
  );
  const response = await verifyContract(etherscanAPIEndpoint, request);

  console.log(
    `Successfully submitted source code for contract
${contractInformation.contractFilename}:${contractInformation.contractName} at ${address}
for verification on etherscan. Waiting for verification result...`
  );

  const pollRequest = toCheckStatusRequest({
    apiKey: etherscan.apiKey,
    guid: response.message,
  });

  // Compilation is bound to take some time so there's no sense in requesting status immediately.
  await delay(700);
  const verificationStatus = await getVerificationStatus(
    etherscanAPIEndpoint,
    pollRequest
  );

  if (verificationStatus.isVerificationSuccess()) {
    console.log("Successfully verified contract on etherscan");
  } else {
    // Reaching this branch shouldn't be possible unless the API is behaving in a new way.
    throw new NomicLabsBuidlerPluginError(
      pluginName,
      `The API responded with an unexpected message.
Contract verification may have succeeded and should be checked manually.
Message: ${verificationStatus.message}`,
      undefined,
      true
    );
  }
};

task("verify", "Verifies contract on etherscan")
  .addPositionalParam(
    "address",
    "Address of the smart contract that will be verified"
  )
  .addOptionalParam(
    "constructorArgs",
    "File path to a javascript module that exports the list of arguments."
  )
  .addOptionalVariadicPositionalParam(
    "constructorArguments",
    "Arguments used in the contract constructor. These are ignored if the --constructorArgs option is passed.",
    []
  )
  .setAction(verify);
