[package]
name = "edr_provider"
version = "0.2.0-dev"
edition = "2021"

[dependencies]
edr_eth = { version = "0.2.0-dev", path = "../edr_eth" }
edr_evm = { version = "0.2.0-dev", path = "../edr_evm" }
rpc_hardhat = { package = "edr_rpc_hardhat", version = "0.2.0-dev", path = "../edr_rpc_hardhat" }
indexmap = { version = "2.0.0", default-features = false, features = ["std"] }
k256 = { version = "0.13.1", default-features = false, features = ["arithmetic", "ecdsa", "pkcs8", "precomputed-tables", "std"] }
log = { version = "0.4.20", default-features = false }
parking_lot = { version = "0.12.1", default-features = false }
rand = { version = "0.8.5", default-features = false }
rlp = { version = "0.5.2", default-features = false }
serde = { version = "1.0.147", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.89" }
sha3 = { version = "0.10.6", default-features = false }
thiserror = { version = "1.0.37", default-features = false }
tokio = { version = "1.21.2", default-features = false, features = ["macros"] }

[dev-dependencies]
anyhow = "1.0.75"
tempfile = "3.7.1"

[build-dependencies]
cargo_toml = { version = "0.15.3", default-features = false }
toml = { version = "0.5.9", default-features = false }
