name: Deploy after Hardhat release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'hardhat@3.')
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: curl --silent --show-error --fail --output /dev/null -X POST "${{ secrets.VERCEL_DEPLOY_AFTER_HARDHAT_RELEASE_WEBHOOK }}"
      - name: Notify failures
        if: failure()
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.GH_ACTION_NOTIFICATIONS_SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "workflow_name": "${{ github.workflow }}",
              "run_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
