name: Populate cache

on:
  push:
    branches:
      - main
      - pre-release-testing-branch
      - changeset-release/main
    paths:
      - ".github/workflows/populate-cache.yml"
      - "pnpm-lock.yaml"
      - "docs/pnpm-lock.yaml"
  pull_request:
    paths:
      - ".github/workflows/populate-cache.yml"
      - "pnpm-lock.yaml"
      - "docs/pnpm-lock.yaml"
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  cache:
    name: Populate cache
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner: ["ubuntu-latest", "macos-latest", "windows-latest"]
        working-directory: ["", "docs"]
    defaults:
      run:
        working-directory: ${{ matrix.working-directory || github.workspace }}
    steps:
      - uses: actions/checkout@v4
      - id: env
        uses: ./.github/actions/setup-env
        with:
          cache-save: true
          pnpm-lockfile: ${{ matrix.working-directory || '.' }}/pnpm-lock.yaml
          package-json: ${{ matrix.working-directory || '.' }}/package.json
      - name: Install
        if: steps.env.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --prefer-offline
