name: Regression Test

on:
  workflow_call:
    inputs:
      hardhat-ref:
        required: true
        type: string
        default: 'next'
      edr-ref:
        required: false
        type: string
        default: ''
      repositories:
        required: false
        type: string
        default: '["foundry-rs/forge-std",  "transmissions11/solmate",  "Vectorized/solady",  "Uniswap/UniswapX",  "sablier-labs/lockup",  "sablier-labs/v2-periphery",  "PaulRBerg/prb-math",  "PaulRBerg/prb-proxy",  "PaulRBerg/prb-test",  "ProjectOpenSea/seaport",  "kalidao/keep",  "Elytro-eth/soul-wallet-contract",  "pancakeswap/infinity-core",  "pcaversaccio/createx",  "mds1/multicall"]'
      runners:
        required: false
        type: string
        default: '["ubuntu-latest"]'
      commands:
        required: false
        type: string
        default: '["hardhat compile", "hardhat test solidity"]'
  workflow_dispatch:
    inputs:
      hardhat-ref:
        required: true
        type: string
        default: 'next'
      edr-ref:
        required: false
        type: string
        default: ''
      repositories:
        required: false
        type: string
        default: '["foundry-rs/forge-std",  "transmissions11/solmate",  "Vectorized/solady",  "Uniswap/UniswapX",  "sablier-labs/lockup",  "sablier-labs/v2-periphery",  "PaulRBerg/prb-math",  "PaulRBerg/prb-proxy",  "PaulRBerg/prb-test",  "ProjectOpenSea/seaport",  "kalidao/keep",  "Elytro-eth/soul-wallet-contract",  "pancakeswap/infinity-core",  "pcaversaccio/createx",  "mds1/multicall"]'
      runners:
        required: false
        type: string
        default: '["ubuntu-latest"]'
      commands:
        required: false
        type: string
        default: '["hardhat compile", "hardhat test solidity"]'

defaults:
  run:
    shell: bash

jobs:
  build-edr:
    name: Build EDR
    if: inputs.edr-ref
    runs-on: ${{ matrix.context.host }}
    strategy:
      fail-fast: false
      matrix:
        context:
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc
    defaults:
      run:
        working-directory: crates/edr_napi
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NomicFoundation/edr
          ref: ${{ inputs.edr-ref }}
      - uses: ./.github/actions/setup-node
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Add Rust cross-compilation target
        run: rustup target add ${{ matrix.context.target }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Build
        run: |
          pnpm build --target ${{ matrix.context.target }}
          strip *.node
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: edr-${{ matrix.context.runner }}
          path: crates/edr_napi/edr.*.node
          if-no-files-found: error

  publish-edr:
    name: Publish EDR
    needs: [build-edr]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crates/edr_napi
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NomicFoundation/edr
          ref: ${{ inputs.edr-ref }}
      - uses: ./.github/actions/setup-node
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: crates/edr_napi/artifacts
      - name: Install sponge
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils
      - name: Move artifacts
        run: pnpm artifacts
      - name: Create the package
        run: pnpm pack
      - name: Upload the package
        uses: actions/upload-artifact@v4
        with:
          name: edr
          path: crates/edr_napi/edr.*.tgz
          if-no-files-found: error

  build-and-publish-hardhat:
    name: Build and publish Hardhat
    needs: [publish-edr]
    if: (!cancelled() && !contains(inputs.hardhat-ref, 'next') && inputs.edr-ref == '' || needs.publish-edr.result == 'success')
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: v-next/hardhat
    steps:
      - uses: actions/checkout@v4
        with:
          repository: NomicFoundation/hardhat
          ref: ${{ inputs.hardhat-ref }}
      - uses: ./.github/actions/setup-env
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile --prefer-offline
      - name: Download EDR
        if: inputs.edr-ref != ''
        uses: actions/download-artifact@v4
        with:
          name: edr
          path: v-next/hardhat
      - name: Install EDR
        if: inputs.edr-ref != ''
        run: |
          pnpm install edr.*.tgz --save-dev
          rm edr.*.tgz
      - name: Build
        run: pnpm build
      - name: Deploy
        run: |
          pnpm deploy --config.node-linker=hoisted --filter=hardhat --prod bundle.tmp
          rsync -a --exclude node_modules/.pnpm/ --copy-links bundle.tmp/ bundle
        working-directory: ${{ github.workspace }}
      - name: Pack
        run: |
          jq '. + {bundleDependencies: true}' package.json > package.json.tmp && mv package.json.tmp package.json
          npm pack
        working-directory: bundle
      - uses: actions/upload-artifact@v4
        with:
          name: hardhat
          path: bundle/hardhat-*.tgz
          if-no-files-found: error

  test:
    name: Run the test command
    needs: [build-and-publish-hardhat]
    if: (!cancelled() && contains(inputs.hardhat-ref, 'next') || needs.build-and-publish-hardhat.result == 'success')
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        repository: ${{ fromJSON(inputs.repositories) }}
        runner: ${{ fromJSON(inputs.runners) }}
        command: ${{ fromJSON(inputs.commands) }}
        config:
          - repositories:
              foundry-rs/forge-std:
                ref: 8ba9031ffcbe25aa0d1224d3ca263a995026e477
                forge-version: v0.3.0
                ignore: |
                  # 1. Reason: Could not instantiate forked environment with fork url: https://eth-mainnet.alchemyapi.io/v2/WV407BEiBmjNJfKo9Uo_55u0z0ITyCOX
                  # 2. Reason: unknown cheatcode with selector 0x6229498b; you may have a mismatch between the `Vm` interface (likely in `forge-std`) and the `edr_solidity_tests` version
                  test/StdCheats.t.sol
                  test/StdUtils.t.sol # Reason: Could not instantiate forked environment with fork url: https://eth-mainnet.alchemyapi.io/v2/WV407BEiBmjNJfKo9Uo_55u0z0ITyCOX
                  test/StdChains.t.sol # Reason: call did not revert as expected
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.26",
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 200
                        }
                      }
                    },
                    "solidityTest": {
                      "fsPermissions": {
                        "readWrite": [
                          "./"
                        ]
                      },
                      "rpcEndpoints": {
                        "mainnet": "https://eth-mainnet.alchemyapi.io/v2/WV407BEiBmjNJfKo9Uo_55u0z0ITyCOX",
                        "optimism_sepolia": "https://sepolia.optimism.io/",
                        "arbitrum_one_sepolia": "https://sepolia-rollup.arbitrum.io/rpc/",
                        "needs_undefined_env_var": "${UNDEFINED_RPC_URL_PLACEHOLDER}"
                      }
                    }
                  };
                  paths:
                    sources: src
                    tests:
                      solidity: test
                  solidity:
                    version: 0.8.26
                    settings:
                      optimizer:
                        enabled: true
                        runs: 200
                  solidityTest:
                    fsPermissions:
                      readWrite:
                        - ./
                    rpcEndpoints:
                      mainnet: https://eth-mainnet.alchemyapi.io/v2/WV407BEiBmjNJfKo9Uo_55u0z0ITyCOX
                      optimism_sepolia: https://sepolia.optimism.io/
                      arbitrum_one_sepolia: https://sepolia-rollup.arbitrum.io/rpc/
                      needs_undefined_env_var: ${UNDEFINED_RPC_URL_PLACEHOLDER}
              transmissions11/solmate:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src"
                    },
                    "solidity": {
                      "version": "0.8.15",
                      "remappings": [
                        "ds-test/=lib/ds-test/src/"
                      ],
                      "settings": {
                        "optimizer": {
                          "runs": 1000000
                        },
                        "metadata": {
                          "bytecodeHash": "none"
                        }
                      }
                    },
                    "solidityTest": {
                      "testFail": true
                    }
                  };
              Vectorized/solady:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.28",
                      "remappings": [
                        "forge-std=test/utils/forge-std/"
                      ],
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 1000
                        },
                        "evmVersion": "cancun"
                      }
                    },
                    "solidityTest": {
                      "blockGasLimit": BigInt(100000000),
                      "fsPermissions": {
                        "read": [
                          "./test/data"
                        ]
                      },
                      "fuzz": {
                        "runs": 256
                      },
                      "invariant": {
                        "depth": 15,
                        "runs": 10
                      }
                    }
                  };
                ignore: |
                  */*7702*
                  */*Transient*
                  */ext/ithaca/*
                  */ext/zksync/*
              Uniswap/UniswapX:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.24",
                      "remappings": [
                        "ds-test/=lib/forge-std/lib/ds-test/src/",
                        "forge-gas-snapshot/=lib/forge-gas-snapshot/src/",
                        "forge-std/=lib/forge-std/src/",
                        "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
                        "permit2/=lib/permit2/",
                        "solmate/=lib/solmate/",
                        "solarray/=lib/solarray/src/"
                      ],
                      "settings": {
                        "optimizer": {
                          "runs": 1000000
                        }
                      }
                    },
                    "solidityTest": {
                      "ffi": true,
                      "fsPermissions": {
                        "readWrite": [
                          ".forge-snapshots/"
                        ]
                      }
                    }
                  };

                ignore: |
                  */integration/*
              sablier-labs/lockup:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "tests/unit/fuzz"
                      }
                    },
                    "solidity": {
                      "version": "0.8.26",
                      "remappings": [
                        "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
                        "@prb/math/=node_modules/@prb/math/",
                        "forge-std/=node_modules/forge-std/",
                        "solady/=node_modules/solady/",
                        "solarray/=node_modules/solarray/"
                      ],
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 570
                        },
                        "evmVersion": "shanghai",
                        "metadata": {
                          "bytecodeHash": "none"
                        }
                      }
                    },
                    "solidityTest": {
                      "fsPermissions": {
                        "read": [
                          "./out-optimized",
                          "package.json"
                        ],
                        "readWrite": [
                          "./benchmark/results",
                          "./script/"
                        ]
                      },
                      "blockGasLimit": BigInt(9223372036854775807),
                      "fuzz": {
                        "runs": 50,
                        "maxTestRejects": 1000000
                      },
                      "invariant": {
                        "runs": 20,
                        "depth": 20,
                        "failOnRevert": true,
                        "callOverride": false
                      },
                      "sender": "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38",
                      "rpcEndpoints": {
                        "arbitrum": "${ARBITRUM_RPC_URL}",
                        "arbitrum_sepolia": "https://arbitrum-sepolia-rpc.publicnode.com",
                        "avalanche": "${AVALANCHE_RPC_URL}",
                        "base": "https://mainnet.base.org",
                        "base_sepolia": "https://sepolia.base.org",
                        "berachain_artio": "https://bartio.rpc.berachain.com/",
                        "blast": "https://rpc.blast.io",
                        "blast_sepolia": "https://sepolia.blast.io",
                        "bnb": "https://bsc-dataseed.binance.org",
                        "core_dao": "https://rpc.coredao.org",
                        "gnosis": "https://rpc.gnosischain.com",
                        "lightlink": "https://replicator.phoenix.lightlink.io/rpc/v1",
                        "linea": "https://rpc.linea.build",
                        "linea_sepolia": "https://rpc.sepolia.linea.build",
                        "localhost": "http://localhost:8545",
                        "mainnet": "${MAINNET_RPC_URL}",
                        "mode": "https://mainnet.mode.network/",
                        "mode_sepolia": "https://sepolia.mode.network/",
                        "morph": "https://rpc.morphl2.io",
                        "optimism": "${OPTIMISM_RPC_URL}",
                        "optimism_sepolia": "https://sepolia.optimism.io",
                        "polygon": "${POLYGON_RPC_URL}",
                        "scroll": "https://rpc.scroll.io/",
                        "sei": "https://evm-rpc.sei-apis.com",
                        "sei_testnet": "https://evm-rpc.arctic-1.seinetwork.io",
                        "sepolia": "${SEPOLIA_RPC_URL}",
                        "superseed": "https://mainnet.superseed.xyz",
                        "superseed_sepolia": "https://sepolia.superseed.xyz",
                        "taiko_hekla": "https://rpc.hekla.taiko.xyz",
                        "taiko_mainnet": "https://rpc.mainnet.taiko.xyz"
                      }
                    }
                  };
                env: |
                  RPC_URL_MAINNET="https://eth-mainnet.g.alchemy.com/v2/<api-key>"
              sablier-labs/v2-periphery:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.26",
                      "remappings": [
                        "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
                        "@prb/math/=node_modules/@prb/math/",
                        "@sablier/v2-core/=node_modules/@sablier/v2-core/",
                        "forge-std/=node_modules/forge-std/",
                        "solady/=node_modules/solady/"
                      ],
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 10000
                        },
                        "evmVersion": "shanghai",
                        "metadata": {
                          "bytecodeHash": "none"
                        }
                      }
                    },
                    "solidityTest": {
                      "blockTimestamp": BigInt(1714518000),
                      "fsPermissions": {
                        "read": [
                          "./out-optimized",
                          "package.json"
                        ],
                        "readWrite": [
                          "./benchmark/results",
                          "./cache"
                        ]
                      },
                      "blockGasLimit": BigInt(9223372036854775807),
                      "sender": "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38",
                      "fuzz": {
                        "runs": 20,
                        "maxTestRejects": 1000000
                      },
                      "rpcEndpoints": {
                        "arbitrum": "${ARBITRUM_RPC_URL}",
                        "arbitrum_sepolia": "https://arbitrum-sepolia.blockpi.network/v1/rpc/public",
                        "avalanche": "${AVALANCHE_RPC_URL}",
                        "base": "https://mainnet.base.org",
                        "base_sepolia": "https://sepolia.base.org",
                        "bnb": "https://bsc-dataseed.binance.org",
                        "gnosis": "https://rpc.gnosischain.com",
                        "localhost": "http://localhost:8545",
                        "mainnet": "${MAINNET_RPC_URL}",
                        "optimism": "${OPTIMISM_RPC_URL}",
                        "optimism_sepolia": "https://sepolia.optimism.io",
                        "polygon": "${POLYGON_RPC_URL}",
                        "scroll": "https://rpc.scroll.io/",
                        "sepolia": "${SEPOLIA_RPC_URL}"
                      }
                    }
                  };
                env: |
                  RPC_URL_MAINNET="https://eth-mainnet.g.alchemy.com/v2/<api-key>"
              PaulRBerg/prb-math:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.26",
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 1000000
                        },
                        "evmVersion": "shanghai"
                      }
                    },
                    "solidityTest": {
                      "fuzz": {
                        "runs": 256
                      }
                    }
                  };
              PaulRBerg/prb-proxy:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.23",
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 200
                        },
                        "evmVersion": "paris",
                        "metadata": {
                          "bytecodeHash": "none",
                          "appendCBOR": false
                        }
                      }
                    },
                    "solidityTest": {
                      "fuzz": {
                        "runs": 1000,
                        "maxTestRejects": 1000000
                      },
                      "fsPermissions": {
                        "read": [
                          "./out-optimized"
                        ]
                      },
                      "rpcEndpoints": {
                        "arbitrum": "https://arbitrum-mainnet.infura.io/v3/${API_KEY_INFURA}",
                        "avalanche": "https://avalanche-mainnet.infura.io/v3/${API_KEY_INFURA}",
                        "bnb_smart_chain": "https://bsc-dataseed.binance.org",
                        "gnosis_chain": "https://rpc.gnosischain.com",
                        "goerli": "https://goerli.infura.io/v3/${API_KEY_INFURA}",
                        "localhost": "http://localhost:8545",
                        "mainnet": "https://eth-mainnet.g.alchemy.com/v2/${API_KEY_ALCHEMY}",
                        "optimism": "https://optimism-mainnet.infura.io/v3/${API_KEY_INFURA}",
                        "polygon": "https://polygon-mainnet.infura.io/v3/${API_KEY_INFURA}",
                        "sepolia": "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
                      }
                    }
                  };
              PaulRBerg/prb-test:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.26",
                      "settings": {
                        "optimizer": {
                          "enabled": false
                        },
                        "evmVersion": "shanghai"
                      }
                    },
                    "solidityTest": {
                      "fuzz": {
                        "runs": 100,
                        "maxTestRejects": 100000
                      }
                    }
                  };
              ProjectOpenSea/seaport:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "contracts",
                      "tests": {
                        "solidity": "test/foundry"
                      }
                    },
                    "solidity": {
                      "version": "0.8.24",
                      "remappings": [
                        "@rari-capital/solmate/=lib/solmate/",
                        "ds-test/=lib/ds-test/src/",
                        "forge-std/=lib/forge-std/src/",
                        "murky/=lib/murky/src/",
                        "@openzeppelin/=lib/openzeppelin-contracts/",
                        "solarray/=lib/solarray/src/",
                        "solady/=lib/solady/",
                        "seaport-sol/=lib/seaport-sol/",
                        "seaport-types/=lib/seaport-types/",
                        "seaport-core/=lib/seaport-core/",
                        "seaport/=contracts/"
                      ],
                      "settings": {
                        "evmVersion": "cancun",
                        "optimizer": {
                          "runs": 4294967292
                        }
                      }
                    },
                    "solidityTest": {
                      "fuzz": {
                        "runs": 1000
                      },
                      "fsPermissions": {
                        "read": [
                          "./optimized-out",
                          "./reference-out"
                        ],
                        "write": [
                          "./call-metrics.txt",
                          "./mutation-metrics.txt",
                          "./assume-metrics.txt",
                          "./fuzz_debug.json"
                        ]
                      }
                    }
                  };
              kalidao/keep:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "contracts",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.18",
                      "remappings": [
                        "@std/=lib/forge-std/src/",
                        "@solady/=lib/solady/",
                        "ds-test/=lib/forge-std/lib/ds-test/src/",
                        "forge-std/=lib/forge-std/src/"
                      ],
                      "settings": {
                        "optimizer": {
                          "runs": 9999999
                        }
                      }
                    },
                    "solidityTest": {
                      "testFail": true
                    }
                  };
              Elytro-eth/soul-wallet-contract:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "contracts",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.24",
                      "remappings": [
                        "@soulwallet-core/=lib/soulwallet-core/",
                        "@source/=contracts/",
                        "@arbitrum/nitro-contracts=lib/nitro-contracts/",
                        "@solady=lib/solady/",
                        "@solenv=lib/solenv/src/",
                        "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
                        "@account-abstraction/=lib/account-abstraction/",
                        "@crypto-lib/=lib/crypto-lib/src/",
                        "forge-std/=lib/forge-std/src/",
                        "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
                      ],
                      "settings": {
                        "viaIR": true,
                        "optimizer": {
                          "enabled": true,
                          "runs": 100000
                        },
                        "evmVersion": "cancun",
                        "metadata": {
                          "bytecodeHash": "none",
                          "appendCBOR": false
                        }
                      }
                    },
                    "solidityTest": {
                      "testFail": true,
                      "rpcEndpoints": {
                        "goerli": "${GOERLI_RPC_URL}",
                        "arbitrumgoerli": "${ARBITRUM_GOERLI_RPC_URL}",
                        "optimismgoerli": "${OPTIMISM_GOERLI_RPC_URL}",
                        "etherum": "${ETHERUM_RPC_URL}",
                        "arbitrum": "${ARBITRUM_RPC_URL}",
                        "optimism": "${OPTIMISM_RPC_URL}",
                        "scrollsepolia": "${SCROLL_SEPOLIA_RPC_URL}",
                        "basesepolia": "${BASE_SEPOLIA_RPC_URL}"
                      }
                    }
                  };
              pancakeswap/infinity-core:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.26",
                      "remappings": [
                        "ds-test/=lib/forge-std/lib/ds-test/src/",
                        "forge-std/=lib/forge-std/src/",
                        "@openzeppelin/=lib/openzeppelin-contracts/",
                        "solmate/=lib/solmate/",
                        "forge-gas-snapshot/=lib/forge-gas-snapshot/src/"
                      ],
                      "settings": {
                        "viaIR": true,
                        "optimizer": {
                          "runs": 25666
                        },
                        "evmVersion": "cancun",
                        "metadata": {
                          "bytecodeHash": "none"
                        }
                      }
                    },
                    "solidityTest": {
                      "testFail": true,
                      "ffi": true,
                      "fsPermissions": {
                        "readWrite": [
                          ".forge-snapshots/"
                        ],
                        "read": [
                          "./foundry-out",
                          "./script/config",
                          "./test/pool-cl/bin",
                          "./test/pool-bin/bin"
                        ]
                      },
                      "blockGasLimit": BigInt(300000000),
                      "fuzz": {
                        "runs": 5
                      }
                    }
                  };
              pcaversaccio/createx:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src",
                      "tests": {
                        "solidity": "test"
                      }
                    },
                    "solidity": {
                      "version": "0.8.23",
                      "remappings": [
                        "solady/=lib/solady/src/",
                        "forge-std/=lib/forge-std/src/",
                        "openzeppelin/=lib/openzeppelin-contracts/contracts/"
                      ],
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 10000000
                        },
                        "viaIR": false,
                        "evmVersion": "paris",
                        "metadata": {
                          "bytecodeHash": "none"
                        }
                      }
                    },
                    "solidityTest": {
                      "fuzz": {
                        "runs": 100
                      },
                      "fsPermissions": {
                        "readWrite": [
                          "./"
                        ]
                      },
                      "invariant": {
                        "runs": 256,
                        "depth": 15
                      }
                    }
                  };
              mds1/multicall:
                hardhat-config: |
                  export default {
                    "paths": {
                      "sources": "src"
                    },
                    "solidity": {
                      "version": "0.8.12",
                      "settings": {
                        "optimizer": {
                          "enabled": true,
                          "runs": 10000000
                        }
                      },
                      "remappings": [
                        "forge-std/=lib/forge-std/src/",
                        "ds-test/=lib/forge-std/lib/ds-test/src/"
                      ]
                    },
                    "solidityTest": {
                      "fuzz": {
                        "runs": 1000
                      }
                    }
                  };
            runners:
              ubuntu-latest: {}
              windows-latest: {}
              macos-latest: {}
            commands:
              forge build:
                pattern: 'Compiling (\d+) files with Solc \d+\.\d+'
                template: 'Compiled ${0} file(s)'
              forge test:
                pattern: 'Ran \d+ test suites in \d+\.\d+m?s \(\d+\.\d+m?s CPU time\): (\d+) tests passed, (\d+) failed, (\d+) skipped \((\d+) total tests\)'
                template: 'Ran ${3} tests (${0} passed, ${1} failed, ${2} skipped)'
              hardhat compile:
                pattern: 'Compiled (\d+) Solidity files with solc \d+\.\d+'
                template: 'Compiled ${0} file(s)'
              hardhat test solidity:
                pattern: 'Run (?:Failed|Passed): (\d+) tests, (\d+) passed, (\d+) failed, (\d+) skipped \(duration: \d+ ms\)'
                template: 'Ran ${0} tests (${1} passed, ${2} failed, ${3} skipped)'
    steps:
      - id: config
        env:
          REPOSITORY: ${{ matrix.repository }}
          RUNNER: ${{ matrix.runner }}
          COMMAND: ${{ matrix.command }}
          CONFIG: ${{ toJSON(matrix.config) }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const config = JSON.parse(process.env.CONFIG);
            const repositoryConfig = config.repositories[process.env.REPOSITORY];
            const runnerConfig = config.runners[process.env.RUNNER];
            const commandConfig = config.commands[process.env.COMMAND];
            if (!repositoryConfig) {
              core.setFailed(`Unsupported repository: ${process.env.REPOSITORY}`);
            }
            if (!runnerConfig) {
              core.setFailed(`Unsupported runner: ${process.env.RUNNER}`);
            }
            if (!commandConfig) {
              core.setFailed(`Unsupported command: ${process.env.COMMAND}`);
            }
            core.setOutput('repository', JSON.stringify(repositoryConfig));
            core.setOutput('runner', JSON.stringify(runnerConfig));
            core.setOutput('command', JSON.stringify(commandConfig));
            console.log({
              repository: repositoryConfig,
              runner: runnerConfig,
              command: commandConfig,
            })
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          repository: ${{ matrix.repository }}
          ref: ${{ fromJSON(steps.config.outputs.repository).ref }}
      - name: Update the .gitignore
        if: fromJSON(steps.config.outputs.repository).ignore != ''
        env:
          IGNORE: ${{ fromJSON(steps.config.outputs.repository).ignore }}
        run: |
          echo "$IGNORE" | tee -a .gitignore
          git clean -fdX
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Download Hardhat
        if: (startsWith(matrix.command, 'hardhat') && !contains(inputs.hardhat-ref, 'next'))
        uses: actions/download-artifact@v4
        with:
          name: hardhat
      - name: Install Hardhat
        if: (startsWith(matrix.command, 'hardhat') && !contains(inputs.hardhat-ref, 'next'))
        run: |
          npm install -g hardhat-*.tgz
          rm hardhat-*.tgz
      - name: Install Hardhat
        if: (startsWith(matrix.command, 'hardhat') && contains(inputs.hardhat-ref, 'next'))
        run: |
          npm install -g hardhat@${{ inputs.hardhat-ref }}
          hardhat --version
      - name: Configure Hardhat
        if: startsWith(matrix.command, 'hardhat')
        env:
          CONFIG: ${{ fromJSON(steps.config.outputs.repository).hardhat-config }}
        run: |
          rm hardhat.config.* || true
          echo "$CONFIG" > hardhat.config.js
      - name: Initialize the package
        if: startsWith(matrix.command, 'hardhat')
        run: |
          npm init -y
          npm pkg set type="module"
      - name: Install dependencies (npm)
        if: hashFiles('package-lock.json') != ''
        run: npm ci
      - name: Install dependencies (pnpm)
        if: hashFiles('pnpm-lock.yaml') != ''
        run: |
          npm install -g pnpm
          pnpm install --frozen-lockfile --prefer-offline || pnpm install
      - name: Install dependencies (yarn)
        if: hashFiles('yarn.lock') != ''
        run: |
          npm install -g yarn
          yarn install --immutable
      - name: Install dependencies (bun)
        if: hashFiles('bun.lockb') != ''
        run: |
          npm install -g bun
          bun install --frozen-lockfile
      - name: Install Forge
        if: startsWith(matrix.command, 'forge')
        uses: foundry-rs/foundry-toolchain@de808b1eea699e761c404bda44ba8f21aba30b2c
        with:
          version: ${{ fromJSON(steps.config.outputs.repository).forge-version }}
          cache: false
      - name: Run ${{ matrix.command }}
        id: run
        env:
          DEBUG: ${{ true && '*' || '' }}
          NODE_OPTIONS: ${{ true && '--trace-warnings --trace-deprecation --trace-exit' || '' }}
          ENV_SOURCE: ${{ fromJSON(steps.config.outputs.repository).env }}
        run: |
          source <(echo "$ENV_SOURCE")
          before=$(date +%s)
          { ${{ matrix.command }} 2>&1 || exit_code=$?; } | tee -a run.output
          exit_code=${exit_code:-0}
          after=$(date +%s)
          echo '{"exit_code": '"$exit_code"', "time": '"$((after - before))"'}' > run.result
          exit $exit_code
        continue-on-error: true
      - name: Run the command post-hook
        uses: actions/github-script@v7
        env:
          PATTERN: ${{ fromJSON(steps.config.outputs.command).pattern }}
          TEMPLATE: ${{ fromJSON(steps.config.outputs.command).template }}
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const output = fs.readFileSync('run.output').toString();
            const matches = output.matchAll(new RegExp(process.env.PATTERN, 'g'));
            const sums = [];
            for (const groups of matches) {
              for (let i = 1; i < groups.length; i++) {
                while (sums.length < i) {
                  sums.push(0);
                }
                sums[i - 1] += parseInt(groups[i]);
              }
            }
            let details = process.env.TEMPLATE;
            for (let i = 0; i < sums.length; i++) {
              details = details.replaceAll(`\${${i}}`, sums[i]);
            }
            fs.writeFileSync('run.details', details);
      - id: upload
        env:
          REPOSITORY: ${{ matrix.repository }}
          CONTEXT: |
            {
              "repository": "${{ matrix.repository }}",
              "runner": "${{ matrix.runner }}",
              "command": "${{ matrix.command }}"
            }
        run: |
          echo "repository=${REPOSITORY//\//_}" | tee -a $GITHUB_OUTPUT
          echo "$CONTEXT" > run.context
      - name: Upload the result
        uses: actions/upload-artifact@v4
        with:
          name: repository-${{ steps.upload.outputs.repository }};command-${{ matrix.command }};runner-${{ matrix.runner }}
          path: |
            run.context
            run.output
            run.result
            run.details

  summarize:
    name: Summarize the test results
    if: (!cancelled())
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Download the results
        uses: actions/download-artifact@v4
        with:
          pattern: '*'
      - name: Summarize the results
        id: summary
        env:
          HARDHAT_REF: ${{ inputs.hardhat-ref }}
          EDR_REF: ${{ inputs.edr-ref }}
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            const artifacts = fs.readdirSync(process.env.GITHUB_WORKSPACE);
            const results = [];
            for (const artifact of artifacts) {
              const context = JSON.parse(fs.readFileSync(path.join(artifact, 'run.context')).toString());
              const result = JSON.parse(fs.readFileSync(path.join(artifact, 'run.result')).toString());
              const details = fs.readFileSync(path.join(artifact, 'run.details')).toString();
              results.push({
                repository: context.repository,
                command: context.command,
                runner: context.runner,
                result: result.exit_code,
                time: result.time,
                details,
              });
            }
            console.log(results);
            const header = ['Repository 📦', 'Command 👾', 'Runner 💨', 'Result 🧪', 'Wall-clock Time ⏰', 'Details 🔎'].map(data => ({data, header: true}));
            const rows = results.map(({repository, command, runner, result, time, details}) => ([
              repository,
              command,
              (() => {
                switch (runner) {
                  case 'ubuntu-latest':
                    return 'Ubuntu 🐧';
                  case 'macos-latest':
                    return 'macOS 🍎';
                  case 'windows-latest':
                    return 'Windows 🪟';
                }
              })(),
              (() => {
                switch (result) {
                  case 0:
                    return '✅ Passed';
                  case 1:
                    return '❌ Failed';
                  default:
                    return `⚠️ Unknown (${result})`;
                }
              })(),
              `${time} s`,
              details,
            ]));
            console.log(header);
            console.log(rows);
            await core.summary
              .addHeading('Test Results')
              .addTable([
                header,
                ...rows,
              ])
              .write()
