name: Check Spelling

on:
  push:
    branches:
      - main
      - v2
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile --prefer-offline

      - run: pnpm spellcheck
