name: "Close stale issues and PR"
on:
  schedule:
    - cron: "30 * * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          stale-issue-message: ""
          stale-pr-message: ""
          close-issue-message: "This issue was closed because it has been stalled for 7 days with no activity."
          close-pr-message: "This PR was closed because it has been stalled for 7 days with no activity."
          days-before-stale: 30
          days-before-close: -1
          exempt-issue-labels: not-stale
          exempt-pr-labels: not-stale
